"""
Moira public package surface.

This module is intentionally thin. The heavyweight facade implementation lives
in ``moira.facade``; subsystem APIs are imported from their owning modules.
"""

import sys as _sys
from ._kernel_paths import find_planetary_kernel as _find_planetary_kernel

if _find_planetary_kernel() is None:
    print(
        "\n"
        "  [moira] WARNING: no planetary kernel is installed.\n"
        "  Most Moira features will fail until you install a compatible JPL SPK kernel.\n"
        "  Run the following command to download one:\n"
        "\n"
        "      moira-download-kernels\n"
        "\n"
        "  Or, inside Python:\n"
        "\n"
        "      from moira.download_kernels import download_missing\n"
        "      download_missing()\n",
        file=_sys.stderr,
    )

del _sys, _find_planetary_kernel

from .constants import Body, HouseSystem
from .facade import Chart, MissingEphemerisKernelError, Moira, __author__, __version__
from .houses import HouseCusps
from .julian import (
    CalendarDateTime,
    DeltaTPolicy,
    apparent_sidereal_time_at,
    calendar_datetime_from_jd,
    calendar_from_jd,
    datetime_from_jd,
    delta_t,
    delta_t_from_jd,
    format_jd_utc,
    greenwich_mean_sidereal_time,
    jd_from_datetime,
    julian_day,
    local_sidereal_time,
    safe_datetime_from_jd,
)
from .nodes import NodeData, NodesAndApsides, nodes_and_apsides_at
from .phenomena import PlanetPhenomena, planet_phenomena_at
from .orbits import DistanceExtremes, KeplerianElements, distance_extremes_at, orbital_elements_at
from .planets import CartesianPosition, PlanetData, SkyPosition
from .sidereal import Ayanamsa, ayanamsa, list_ayanamsa_systems, sidereal_to_tropical, tropical_to_sidereal, nakshatra_of, all_nakshatras_at
from .aspects import AspectData
from .harmograms import (
    HarmogramChartDomain,
    HarmogramIntensityFamily,
    HarmogramIntensityPolicy,
    HarmogramPolicy,
    HarmogramTraceFamily,
    HarmonicDomain,
    PointSetHarmonicVectorPolicy,
    harmogram_trace,
    intensity_function_spectrum,
    parts_from_zero_aries,
    point_set_harmonic_vector,
    project_harmogram_strength,
    zero_aries_parts_harmonic_vector,
)
from .vedic_dignities import (
    VedicDignityRank,
    CompoundRelationship,
    DignityTier,
    EXALTATION_SIGN,
    EXALTATION_DEGREE,
    DEBILITATION_SIGN,
    MULATRIKONA_SIGN,
    MULATRIKONA_START,
    MULATRIKONA_END,
    OWN_SIGNS,
    NATURAL_FRIENDS,
    NATURAL_NEUTRALS,
    NATURAL_ENEMIES,
    VedicDignityResult,
    PlanetaryRelationship,
    VedicDignityPolicy,
    DignityConditionProfile,
    ChartDignityProfile,
    vedic_dignity,
    planetary_relationships,
    dignity_condition_profile,
    chart_dignity_profile,
    validate_dignity_output,
)
from .jaimini import (
    KARAKA_NAMES_7,
    KARAKA_NAMES_8,
    KarakaRole,
    KarakaPlanetType,
    JaiminiPolicy,
    KarakaAssignment,
    JaiminiKarakaResult,
    KarakaConditionProfile,
    JaiminiChartProfile,
    KarakaPair,
    jaimini_karakas,
    atmakaraka,
    karaka_condition_profile,
    jaimini_chart_profile,
    karaka_pair,
    validate_jaimini_output,
)
from .panchanga import (
    TithiPaksha,
    YogaClass,
    KaranaType,
    VaraLordType,
    PanchangaPolicy,
    TITHI_NAMES,
    YOGA_NAMES,
    KARANA_NAMES,
    VARA_LORDS,
    VARA_NAMES,
    PanchangaElement,
    PanchangaResult,
    TithiConditionProfile,
    PanchangaProfile,
    panchanga_at,
    tithi_condition_profile,
    panchanga_profile,
    validate_panchanga_output,
)
from .dasha_systems import (
    ASHTOTTARI_YEARS,
    ASHTOTTARI_SEQUENCE,
    ASHTOTTARI_NAKSHATRA_LORD,
    ASHTOTTARI_TOTAL,
    YOGINI_YEARS,
    YOGINI_SEQUENCE,
    YOGINI_PLANETS,
    YOGINI_TOTAL,
    AlternateDashaPeriod,
    AlternatePeriodProfile,
    AlternateDashaSequenceProfile,
    AshtottariPolicy,
    YoginiPolicy,
    ashtottari,
    yogini_dasha,
    alternate_period_profile,
    alternate_sequence_profile,
    validate_alternate_dasha_output,
)
from .ashtakavarga import (
    REKHA_TABLES,
    AshtakavargaChartProfile,
    AshtakavargaPolicy,
    AshtakavargaResult,
    BhinnashtakavargaResult,
    RekhaTier,
    SignStrengthProfile,
    ashtakavarga,
    ashtakavarga_chart_profile,
    bhinnashtakavarga,
    sign_strength_profile,
    transit_strength,
    validate_ashtakavarga_output,
)
from .shadbala import (
    NAISARGIKA_BALA,
    REQUIRED_RUPAS,
    MEAN_DAILY_MOTION,
    ShadbalaTier,
    SthanaBala,
    KalaBala,
    PlanetShadbala,
    ShadbalaResult,
    ShadbalaPolicy,
    ShadbalaConditionProfile,
    ShadbalaChartProfile,
    sthana_bala,
    dig_bala,
    kala_bala,
    chesta_bala,
    drig_bala,
    shadbala,
    hora_lord_at,
    shadbala_condition_profile,
    shadbala_chart_profile,
    validate_shadbala_output,
)
from .heliacal import (
    # concrete planet wrappers (V0 baseline)
    PlanetHeliacalEvent,
    planet_acronychal_rising,
    planet_acronychal_setting,
    planet_heliacal_rising,
    planet_heliacal_setting,
    # V5 generalized visibility surface
    HeliacalEventKind,
    VisibilityTargetKind,
    LightPollutionClass,
    LightPollutionDerivationMode,
    ObserverAid,
    ObserverVisibilityEnvironment,
    VisibilityCriterionFamily,
    VisibilityExtinctionModel,
    VisibilityTwilightModel,
    ExtinctionCoefficient,
    MoonlightPolicy,
    VisibilityPolicy,
    VisibilitySearchPolicy,
    LunarCrescentVisibilityClass,
    LunarCrescentDetails,
    VisibilityAssessment,
    GeneralVisibilityEvent,
    visibility_assessment,
    visual_limiting_magnitude,
    visibility_event,
)
from .hermetic_decans import (
    DecanHour,
    DecanHoursNight,
    DECAN_NAMES,
    DECAN_RULING_STARS,
    list_decans,
    available_decans,
    decan_for_longitude,
    decan_at,
    decan_hours,
)

__all__ = [
    "Moira",
    "Chart",
    "MissingEphemerisKernelError",
    "Body",
    "HouseSystem",
    "Ayanamsa",
    "PlanetData",
    "SkyPosition",
    "CartesianPosition",
    "NodeData",
    "NodesAndApsides",
    "nodes_and_apsides_at",
    "PlanetPhenomena",
    "planet_phenomena_at",
    "HouseCusps",
    "AspectData",
    "HarmonicDomain",
    "PointSetHarmonicVectorPolicy",
    "HarmogramIntensityFamily",
    "HarmogramChartDomain",
    "HarmogramTraceFamily",
    "HarmogramIntensityPolicy",
    "HarmogramPolicy",
    "point_set_harmonic_vector",
    "parts_from_zero_aries",
    "zero_aries_parts_harmonic_vector",
    "intensity_function_spectrum",
    "project_harmogram_strength",
    "harmogram_trace",
    "PlanetHeliacalEvent",
    "planet_heliacal_rising",
    "planet_heliacal_setting",
    "planet_acronychal_rising",
    "planet_acronychal_setting",
    # V5 generalized visibility surface
    "HeliacalEventKind",
    "VisibilityTargetKind",
    "LightPollutionClass",
    "LightPollutionDerivationMode",
    "ObserverAid",
    "ObserverVisibilityEnvironment",
    "VisibilityCriterionFamily",
    "VisibilityExtinctionModel",
    "VisibilityTwilightModel",
    "ExtinctionCoefficient",
    "MoonlightPolicy",
    "VisibilityPolicy",
    "VisibilitySearchPolicy",
    "LunarCrescentVisibilityClass",
    "LunarCrescentDetails",
    "VisibilityAssessment",
    "GeneralVisibilityEvent",
    "visibility_assessment",
    "visual_limiting_magnitude",
    "visibility_event",
    # Hermetic decans
    "DecanHour",
    "DecanHoursNight",
    "DECAN_NAMES",
    "DECAN_RULING_STARS",
    "list_decans",
    "available_decans",
    "decan_for_longitude",
    "decan_at",
    "decan_hours",
    "KeplerianElements",
    "DistanceExtremes",
    "CalendarDateTime",
    "DeltaTPolicy",
    "julian_day",
    "calendar_from_jd",
    "calendar_datetime_from_jd",
    "jd_from_datetime",
    "datetime_from_jd",
    "format_jd_utc",
    "safe_datetime_from_jd",
    "greenwich_mean_sidereal_time",
    "local_sidereal_time",
    "apparent_sidereal_time_at",
    "delta_t",
    "delta_t_from_jd",
    "orbital_elements_at",
    "distance_extremes_at",
    "ayanamsa",
    "tropical_to_sidereal",
    "sidereal_to_tropical",
    "list_ayanamsa_systems",
    "nakshatra_of",
    "all_nakshatras_at",
    # Vedic dignities
    "VedicDignityRank",
    "CompoundRelationship",
    "DignityTier",
    "EXALTATION_SIGN",
    "EXALTATION_DEGREE",
    "DEBILITATION_SIGN",
    "MULATRIKONA_SIGN",
    "MULATRIKONA_START",
    "MULATRIKONA_END",
    "OWN_SIGNS",
    "NATURAL_FRIENDS",
    "NATURAL_NEUTRALS",
    "NATURAL_ENEMIES",
    "VedicDignityResult",
    "PlanetaryRelationship",
    "VedicDignityPolicy",
    "DignityConditionProfile",
    "ChartDignityProfile",
    "vedic_dignity",
    "planetary_relationships",
    "dignity_condition_profile",
    "chart_dignity_profile",
    "validate_dignity_output",
    # Jaimini karakas
    "KARAKA_NAMES_7",
    "KARAKA_NAMES_8",
    "KarakaRole",
    "KarakaPlanetType",
    "JaiminiPolicy",
    "KarakaAssignment",
    "JaiminiKarakaResult",
    "KarakaConditionProfile",
    "JaiminiChartProfile",
    "KarakaPair",
    "jaimini_karakas",
    "atmakaraka",
    "karaka_condition_profile",
    "jaimini_chart_profile",
    "karaka_pair",
    "validate_jaimini_output",
    # Panchanga
    "TithiPaksha",
    "YogaClass",
    "KaranaType",
    "VaraLordType",
    "PanchangaPolicy",
    "TITHI_NAMES",
    "YOGA_NAMES",
    "KARANA_NAMES",
    "VARA_LORDS",
    "VARA_NAMES",
    "PanchangaElement",
    "PanchangaResult",
    "TithiConditionProfile",
    "PanchangaProfile",
    "panchanga_at",
    "tithi_condition_profile",
    "panchanga_profile",
    "validate_panchanga_output",
    # Dasha systems
    "ASHTOTTARI_YEARS",
    "ASHTOTTARI_SEQUENCE",
    "ASHTOTTARI_NAKSHATRA_LORD",
    "ASHTOTTARI_TOTAL",
    "YOGINI_YEARS",
    "YOGINI_SEQUENCE",
    "YOGINI_PLANETS",
    "YOGINI_TOTAL",
    "AlternateDashaPeriod",
    "AlternatePeriodProfile",
    "AlternateDashaSequenceProfile",
    "AshtottariPolicy",
    "YoginiPolicy",
    "ashtottari",
    "yogini_dasha",
    "alternate_period_profile",
    "alternate_sequence_profile",
    "validate_alternate_dasha_output",
    # Ashtakavarga
    "REKHA_TABLES",
    "AshtakavargaChartProfile",
    "AshtakavargaPolicy",
    "AshtakavargaResult",
    "BhinnashtakavargaResult",
    "RekhaTier",
    "SignStrengthProfile",
    "ashtakavarga",
    "ashtakavarga_chart_profile",
    "bhinnashtakavarga",
    "sign_strength_profile",
    "transit_strength",
    "validate_ashtakavarga_output",
    # Shadbala
    "NAISARGIKA_BALA",
    "REQUIRED_RUPAS",
    "MEAN_DAILY_MOTION",
    "ShadbalaTier",
    "SthanaBala",
    "KalaBala",
    "PlanetShadbala",
    "ShadbalaResult",
    "ShadbalaPolicy",
    "ShadbalaConditionProfile",
    "ShadbalaChartProfile",
    "sthana_bala",
    "dig_bala",
    "kala_bala",
    "chesta_bala",
    "drig_bala",
    "shadbala",
    "hora_lord_at",
    "shadbala_condition_profile",
    "shadbala_chart_profile",
    "validate_shadbala_output",
    "__version__",
    "__author__",
]
