"""
moira/comets.py — Comet Oracle

Archetype: Oracle
Purpose: Provides geocentric tropical ecliptic positions for astrologically
         curated periodic comets from a locally generated JPL SPK kernel.

Boundary declaration
--------------------
Owns:
    - COMET_NAIF         — name → NAIF ID mapping for supported comets.
    - CometData          — geocentric ecliptic position result dataclass.
    - load_comet_kernel() — explicit kernel load / reload.
    - comet_at()         — geocentric ecliptic position of one comet at a JD.
    - all_comets_at()    — positions of all (or a subset of) comets at a JD.
    - list_comets()      — all known comet names.
Delegates:
    - SPK file I/O and type 13 segment reading to moira._spk_body_kernel.
    - Earth/Sun barycentric positions to moira.planets / moira.spk_reader.
    - Light-time, aberration, deflection, frame-bias corrections to
      moira.corrections.
    - Precession and nutation matrices to moira.coordinates.
    - Obliquity to moira.obliquity.
    - Precession in longitude to moira.precession.
    - JD conversion to moira.julian.

Import-time side effects:
    - Importing moira._spk_body_kernel registers _Type13Segment in jplephem's
      _segment_classes dict.  This is idempotent.

External dependency assumptions:
    - jplephem must be installed (ImportError raised otherwise).
    - comets.bsp must be present (generated by scripts/build_comet_kernel.py)
      before any position query; FileNotFoundError is raised otherwise.

Public surface / exports:
    CometData             — position result dataclass
    COMET_NAIF            — name → NAIF ID dict
    comet_at()            — single-comet position
    all_comets_at()       — multi-comet positions
    list_comets()         — all known names
    load_comet_kernel()   — explicit kernel load / reload

NAIF ID convention for comets
------------------------------
JPL Horizons assigns comets NAIF IDs in the 1000xxx range (not 2000xxx).
Periodic comet P/N uses NAIF ID 1_000_000 + N, e.g.:
    1P/Halley           → 1000001
    2P/Encke            → 1000002
    9P/Tempel 1         → 1000009
    67P/Churyumov-Gerasimenko → 1000067
    109P/Swift-Tuttle   → 1000109

The kernel file (comets.bsp) must be generated locally via
scripts/build_comet_kernel.py, which fetches Horizons VECTORS for each
comet and writes a type 13 SPK with S/C center = 10 (Sun).

Usage
-----
    from moira.comets import comet_at, all_comets_at, list_comets

    pos = comet_at("Halley", jd_ut)
    print(pos.longitude, pos.sign, pos.retrograde)
"""

from dataclasses import dataclass, field
from pathlib import Path

from .constants import sign_of
from .coordinates import (
    Vec3, vec_add, vec_sub, vec_norm, icrf_to_ecliptic, mat_vec_mul,
    precession_matrix_equatorial, nutation_matrix_equatorial,
)
from .obliquity import mean_obliquity, true_obliquity, nutation
from .precession import general_precession_in_longitude
from .julian import ut_to_tt
from .planets import _earth_barycentric, _barycentric as _planet_barycentric
from ._kernel_paths import find_kernel
from .corrections import (
    apply_light_time, apply_aberration, apply_deflection, apply_frame_bias,
    SCHWARZSCHILD_RADII,
)
from ._spk_body_kernel import SmallBodyKernel  # also registers _Type13Segment


__all__ = [
    "CometData",
    "COMET_NAIF",
    "comet_at",
    "all_comets_at",
    "list_comets",
    "load_comet_kernel",
]


# ---------------------------------------------------------------------------
# Comet NAIF IDs
# ---------------------------------------------------------------------------
# Convention: periodic comet P/N → NAIF ID = 1_000_000 + N
# Verify each against JPL Horizons with a comet search such as
# COMMAND='DES=1P;NOFRAG;CAP' before kernel generation.

COMET_NAIF: dict[str, int] = {
    "Halley":               1000001,   # 1P/Halley
    "Encke":                1000002,   # 2P/Encke
    "Tempel1":              1000009,   # 9P/Tempel 1
    "Churyumov-Gerasimenko": 1000067,  # 67P/C-G
    "Swift-Tuttle":         1000109,   # 109P/Swift-Tuttle
}


# ---------------------------------------------------------------------------
# Default kernel path
# ---------------------------------------------------------------------------

_COMET_KERNEL_PATH = find_kernel("comets.bsp")

_SPEED_STEP = 0.5   # days, for numerical longitude differentiation


# ---------------------------------------------------------------------------
# CometData — position result
# ---------------------------------------------------------------------------

@dataclass
class CometData:
    """
    Geocentric tropical ecliptic position of a comet.

    Fields
    ------
    name        : common name (e.g. "Halley")
    naif_id     : NAIF body ID used to query the kernel
    longitude   : tropical ecliptic longitude in degrees [0, 360)
    latitude    : ecliptic latitude in degrees (−90, +90)
    distance    : geocentric distance in AU
    speed       : daily motion in longitude (degrees/day; negative = retrograde)
    retrograde  : True when speed < 0
    sign        : zodiac sign name
    sign_symbol : zodiac sign Unicode symbol
    """
    name:        str
    naif_id:     int
    longitude:   float
    latitude:    float
    distance:    float
    speed:       float
    retrograde:  bool
    sign:        str
    sign_symbol: str

    def __repr__(self) -> str:
        deg = int(self.longitude)
        rem = (self.longitude - deg) * 60
        m   = int(rem)
        s   = (rem - m) * 60
        r   = "℞" if self.retrograde else "D"
        return (
            f"{self.name}: {deg}°{m:02d}′{s:04.1f}″ {self.sign} {self.sign_symbol}"
            f"  ({self.longitude:.4f}°) {r}  Δ={self.speed:+.4f}°/d"
        )


# ---------------------------------------------------------------------------
# Kernel singleton
# ---------------------------------------------------------------------------

_comet_kernel: SmallBodyKernel | None = None


def load_comet_kernel(path: Path | None = None) -> None:
    """
    Load (or reload) the comet SPK kernel.

    Parameters
    ----------
    path : optional override path; defaults to the configured comets.bsp location.
    """
    global _comet_kernel
    if _comet_kernel is not None:
        _comet_kernel.close()
        _comet_kernel = None
    p = Path(path) if path is not None else _COMET_KERNEL_PATH
    _comet_kernel = SmallBodyKernel(p)


def _get_kernel() -> SmallBodyKernel:
    global _comet_kernel
    if _comet_kernel is None:
        load_comet_kernel()
    return _comet_kernel  # type: ignore[return-value]


# ---------------------------------------------------------------------------
# Heliocentric → geocentric ecliptic pipeline
# ---------------------------------------------------------------------------

def _sun_barycentric(jd_tt: float) -> Vec3:
    """Barycentric ICRF position of the Sun (km)."""
    return _planet_barycentric(10, jd_tt)


def _comet_geocentric_ecliptic(
    naif_id: int,
    jd_ut: float,
    kernel: SmallBodyKernel,
) -> tuple[float, float, float, float]:
    """
    Return (longitude_deg, latitude_deg, distance_au, speed_deg_per_day)
    for *naif_id* at *jd_ut* using the supplied kernel.

    The pipeline mirrors asteroids._compute_asteroid_position() exactly:
    heliocentric ICRF → light-time iteration → aberration → deflection →
    frame bias → precession+nutation → ecliptic.
    """
    jd_tt = ut_to_tt(jd_ut)

    # Earth and Sun barycentric ICRF positions (km)
    earth_bary = _earth_barycentric(jd_tt)
    sun_bary   = _sun_barycentric(jd_tt)

    # Comet heliocentric ICRF (km); kernel center is Sun (NAIF 10)
    comet_helio = kernel.position(naif_id, jd_tt)

    # Barycentric comet position
    comet_bary = vec_add(comet_helio, sun_bary)

    # Geocentric ICRF (initial, no light-time)
    geo = vec_sub(comet_bary, earth_bary)

    # Light-time correction (iterate once)
    geo = apply_light_time(geo, comet_bary, earth_bary, jd_tt,
                           lambda jd: vec_add(kernel.position(naif_id, jd), sun_bary))

    # Stellar aberration
    geo = apply_aberration(geo, jd_tt)

    # Gravitational deflection (Sun only for small bodies)
    geo = apply_deflection(geo, earth_bary, sun_bary, SCHWARZSCHILD_RADII)

    # Frame bias (ICRF → mean J2000)
    geo = apply_frame_bias(geo)

    # Precession + nutation → apparent equatorial of date
    eps   = mean_obliquity(jd_tt)
    _, deps_deg = nutation(jd_tt)
    gp    = general_precession_in_longitude(jd_tt)
    P     = precession_matrix_equatorial(jd_tt)
    N     = nutation_matrix_equatorial(jd_tt)
    geo   = mat_vec_mul(N, mat_vec_mul(P, geo))

    # Equatorial → ecliptic
    lon, lat, dist_km = icrf_to_ecliptic(geo, eps + deps_deg)

    dist_au = dist_km / 149_597_870.7

    # Longitude speed via symmetric finite difference
    def _lon_at(jd_off: float) -> float:
        jd2 = ut_to_tt(jd_ut + jd_off)
        eb  = _earth_barycentric(jd2)
        sb  = _sun_barycentric(jd2)
        ch  = kernel.position(naif_id, jd2)
        cb  = vec_add(ch, sb)
        g   = vec_sub(cb, eb)
        g   = apply_light_time(g, cb, eb, jd2, lambda jd: vec_add(kernel.position(naif_id, jd), sb))
        g   = apply_aberration(g, jd2)
        g   = apply_deflection(g, eb, sb, SCHWARZSCHILD_RADII)
        g   = apply_frame_bias(g)
        eps2 = mean_obliquity(jd2)
        _, deps2 = nutation(jd2)
        P2  = precession_matrix_equatorial(jd2)
        N2  = nutation_matrix_equatorial(jd2)
        g   = mat_vec_mul(N2, mat_vec_mul(P2, g))
        lo, _, _ = icrf_to_ecliptic(g, eps2 + deps2)
        return lo

    lo_m = _lon_at(-_SPEED_STEP)
    lo_p = _lon_at(+_SPEED_STEP)
    raw_speed = (lo_p - lo_m) / (2.0 * _SPEED_STEP)
    # Wrap across 0°/360° boundary
    if raw_speed > 180.0:
        raw_speed -= 360.0
    elif raw_speed < -180.0:
        raw_speed += 360.0

    return lon, lat, dist_au, raw_speed


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def comet_at(name: str, jd_ut: float) -> CometData:
    """
    Return the geocentric tropical ecliptic position of *name* at *jd_ut*.

    Parameters
    ----------
    name   : comet name, must be a key in COMET_NAIF.
    jd_ut  : Julian Date in UT1 / UTC.

    Returns
    -------
    CometData instance.

    Raises
    ------
    KeyError          : if *name* is not in COMET_NAIF.
    FileNotFoundError : if comets.bsp is not present.
    KeyError          : if the kernel has no segment covering *name* at *jd_ut*.
    """
    naif_id = COMET_NAIF[name]
    kernel  = _get_kernel()
    lon, lat, dist, speed = _comet_geocentric_ecliptic(naif_id, jd_ut, kernel)
    sign_name, sign_sym = sign_of(lon)
    return CometData(
        name=name,
        naif_id=naif_id,
        longitude=lon,
        latitude=lat,
        distance=dist,
        speed=speed,
        retrograde=speed < 0.0,
        sign=sign_name,
        sign_symbol=sign_sym,
    )


def all_comets_at(
    jd_ut: float,
    names: set[str] | None = None,
) -> dict[str, CometData]:
    """
    Return positions for all (or a subset of) comets at *jd_ut*.

    Parameters
    ----------
    jd_ut : Julian Date in UT1 / UTC.
    names : optional set of names to query; defaults to all of COMET_NAIF.

    Returns
    -------
    dict mapping name → CometData.  Bodies unavailable in the kernel
    (outside coverage date range) are silently skipped.
    """
    kernel  = _get_kernel()
    targets = names if names is not None else set(COMET_NAIF.keys())
    result: dict[str, CometData] = {}
    for name in targets:
        if name not in COMET_NAIF:
            continue
        naif_id = COMET_NAIF[name]
        if not kernel.has_body(naif_id):
            continue
        try:
            lon, lat, dist, speed = _comet_geocentric_ecliptic(naif_id, jd_ut, kernel)
        except (KeyError, ValueError):
            continue
        sign_name, sign_sym = sign_of(lon)
        result[name] = CometData(
            name=name,
            naif_id=naif_id,
            longitude=lon,
            latitude=lat,
            distance=dist,
            speed=speed,
            retrograde=speed < 0.0,
            sign=sign_name,
            sign_symbol=sign_sym,
        )
    return result


def list_comets() -> list[str]:
    """Return all known comet names (sorted)."""
    return sorted(COMET_NAIF.keys())
