"""
Moira — delta_t_physical.py
The Oracle of ΔT: governs physics-based hybrid Delta T computation by
decomposing ΔT into secular, core-mantle, cryosphere, and residual components.

Boundary: owns the full ΔT decomposition pipeline — secular parabola, core
angular momentum integration, GRACE/GRACE-FO cryosphere contribution, and
IERS residual spline fitting. Delegates IERS measured ΔT lookup to
moira.julian.delta_t (used only during residual spline construction). Does not
own time-scale conversion, calendar arithmetic, or any display formatting.

Public surface:
    secular_trend, core_delta_t, cryo_delta_t, delta_t_hybrid,
    delta_t_hybrid_uncertainty

Import-time side effects: None

External dependency assumptions:
    - scipy.interpolate.UnivariateSpline is required for the modern-era
      residual spline. The hybrid ΔT model must not silently degrade when
      this dependency is absent.
    - Data files under moira/data/ (delta_t_hpiers_2016.txt,
      grace_lod_contribution.txt, core_angular_momentum.txt) are loaded
      lazily on first call via @cache decorated loaders; missing files are
      handled gracefully (empty series / fallback values).
"""

import math
import statistics
from dataclasses import dataclass
from functools import cache
from pathlib import Path

from .constants import JULIAN_YEAR
from .julian import julian_day

__all__ = [
    "TIDAL_COEFF",
    "GIA_COEFF",
    "REFERENCE_LOD",
    "REFERENCE_YEAR",
    "secular_trend",
    "core_delta_t",
    "cryo_delta_t",
    "delta_t_hybrid",
    "delta_t_hybrid_uncertainty",
]


_DATA_DIR = Path(__file__).resolve().parent / "data"

TIDAL_COEFF: float = 31.0
GIA_COEFF: float = -3.0
REFERENCE_LOD: float = 69.3
REFERENCE_YEAR: float = 2026.0

_CORE_COVERAGE_START: float = 1840.0
_CORE_DECORRELATION_YEARS: float = 10.0
_RESIDUAL_FIT_START: float = 1962.5
_RESIDUAL_TAPER_START: float = 2021.5
_RESIDUAL_TAPER_END: float = 2024.5
_GIA_COEFF_SIGMA: float = 0.5
_CRYO_TREND_SIGMA: float = 0.002
_CORE_HISTORICAL_SIGMA: float = 0.3
_RESIDUAL_FUTURE_RMS_FALLBACK: float = 0.4


def _require_univariate_spline() -> type:
    """
    Return scipy's UnivariateSpline or raise a hard runtime error.

    The residual spline is not optional for Moira's asserted hybrid ΔT model.
    If scipy is missing, callers must see a clear failure instead of a silent
    fallback to an incomplete model.
    """
    try:
        from scipy.interpolate import UnivariateSpline
    except ImportError as exc:
        raise RuntimeError(
            "delta_t_hybrid requires scipy.interpolate.UnivariateSpline. "
            "Install Moira runtime dependencies to enable the residual spline."
        ) from exc
    return UnivariateSpline


@dataclass(frozen=True, slots=True)
class _ResidualSplineFit:
    """Internal vessel for the residual spline plus its diagnostics."""
    spline: object | None
    cv_rms: float
    in_sample_rms: float
    knot_count: int


@cache
def _load_smh2016_table() -> tuple[tuple[float, float], ...]:
    path = _DATA_DIR / "delta_t_hpiers_2016.txt"
    rows: dict[float, float] = {}
    for raw in path.read_text(encoding="utf-8").splitlines():
        parts = raw.split()
        if len(parts) < 2:
            continue
        try:
            year = float(parts[0])
            dt = float(parts[1])
        except ValueError:
            continue
        rows[year] = dt
    return tuple(sorted(rows.items()))


def _smh2016_lookup(year: float) -> float:
    """Interpolate the SMH 2016 ΔT table at the given decimal year."""
    table = _load_smh2016_table()
    if not table:
        t = (year - 1820.0) / 100.0
        return -20.0 + 32.0 * t * t
    if year <= table[0][0]:
        return table[0][1]
    if year >= table[-1][0]:
        return table[-1][1]
    for (y0, dt0), (y1, dt1) in zip(table, table[1:]):
        if y0 <= year <= y1:
            frac = (year - y0) / (y1 - y0)
            return dt0 + frac * (dt1 - dt0)
    return table[-1][1]


def secular_trend(year: float) -> float:
    """
    Physics-based secular Delta T trend from tidal braking + GIA.

    Both coefficients are re-expressed around REFERENCE_YEAR after expanding
    the original 1820/2000 reference epochs — the linear and constant terms
    are absorbed into REFERENCE_LOD via the continuity constraint.
    See DELTA_T_HYBRID_MODEL.md section 3, Phase 1 for the full derivation.

    Parameters
    ----------
    year : decimal year

    Returns
    -------
    ΔT in seconds
    """
    t = (year - REFERENCE_YEAR) / 100.0
    return REFERENCE_LOD + (TIDAL_COEFF + GIA_COEFF) * t * t


@cache
def _load_grace_series() -> tuple[tuple[float, float, int], ...]:
    """
    Load pre-processed GRACE/GRACE-FO LOD contribution series.

    File: moira/data/grace_lod_contribution.txt
    Format: decimal_year  cumulative_delta_t_seconds  gap_flag
            where gap_flag=1 means the month was interpolated across the
            2017-10 to 2018-06 GRACE/GRACE-FO gap.

    Generated by: scripts/fetch_grace_j2.py
    Returns empty tuple if the file does not yet exist.
    """
    path = _DATA_DIR / "grace_lod_contribution.txt"
    if not path.exists():
        return ()
    rows: list[tuple[float, float, int]] = []
    for raw in path.read_text(encoding="utf-8").splitlines():
        raw = raw.strip()
        if not raw or raw.startswith("#"):
            continue
        parts = raw.split()
        if len(parts) < 2:
            continue
        try:
            yr = float(parts[0])
            val = float(parts[1])
            flag = int(parts[2]) if len(parts) >= 3 else 0
        except ValueError:
            continue
        rows.append((yr, val, flag))
    rows.sort(key=lambda r: r[0])
    return tuple(rows)


def cryo_delta_t(year: float) -> float:
    """
    Cryosphere/hydrosphere contribution to Delta T from the pre-integrated
    GRACE/GRACE-FO J2 series.

    Returns 0.0 if the data file does not yet exist or if year < GRACE start.
    For years beyond the last GRACE-FO measurement, extrapolates using the
    linear trend of the last 5 years of available data.

    Integration constant: cryo_delta_t(first_epoch) ≡ 0 by construction.
    See DELTA_T_HYBRID_MODEL.md section 3, Phase 2 for details.

    Parameters
    ----------
    year : decimal year

    Returns
    -------
    ΔT contribution in seconds
    """
    series = _load_grace_series()
    if not series:
        return 0.0
    if year <= series[0][0]:
        return 0.0
    if year <= series[-1][0]:
        for i in range(len(series) - 1):
            y0, v0, _ = series[i]
            y1, v1, _ = series[i + 1]
            if y0 <= year <= y1:
                frac = (year - y0) / (y1 - y0)
                return v0 + frac * (v1 - v0)
        return series[-1][1]
    window = [(r[0], r[1]) for r in series if r[0] >= series[-1][0] - 5.0]
    if len(window) < 2:
        return series[-1][1]
    n = len(window)
    mean_y = sum(y for y, _ in window) / n
    mean_v = sum(v for _, v in window) / n
    ss_xy = sum((window[i][0] - mean_y) * (window[i][1] - mean_v) for i in range(n))
    ss_xx = sum((window[i][0] - mean_y) ** 2 for i in range(n))
    if ss_xx == 0.0:
        return series[-1][1]
    slope = ss_xy / ss_xx
    intercept = mean_v - slope * mean_y
    return intercept + slope * year


@cache
def _load_core_series() -> tuple[tuple[float, float], ...]:
    """
    Load the Gillet et al. core angular momentum series.

    File: moira/data/core_angular_momentum.txt
    Format: decimal_year  delta_lod_ms
    Source: Gillet et al. (2019/2022) supplementary tables.
    Returns empty tuple if the file does not yet exist.
    """
    path = _DATA_DIR / "core_angular_momentum.txt"
    if not path.exists():
        return ()
    rows: list[tuple[float, float]] = []
    for raw in path.read_text(encoding="utf-8").splitlines():
        raw = raw.strip()
        if not raw or raw.startswith("#"):
            continue
        parts = raw.split()
        if len(parts) < 2:
            continue
        try:
            yr = float(parts[0])
            lod_ms = float(parts[1])
        except ValueError:
            continue
        rows.append((yr, lod_ms))
    rows.sort(key=lambda r: r[0])
    return tuple(rows)


def _lod_series_to_delta_t(
    series: tuple[tuple[float, float], ...]
) -> tuple[tuple[float, float], ...]:
    """
    Convert a LOD anomaly series (ms/day, annual resolution) to cumulative
    Delta T contribution (seconds) by discrete integration.

    ΔT(y) = Σ (ΔLOD(t_i) - mean_LOD) × Δt_i / 86400
    where Δt_i is days between successive annual epochs.

    The series mean is subtracted before integration so the cumulative
    integral is zero-mean rather than drifting with the absolute LOD
    baseline.  This ensures the core component does not introduce a secular
    offset that duplicates the secular_trend parabola.
    """
    if not series:
        return ()
    mean_lod = sum(lod for _, lod in series) / len(series)
    result: list[tuple[float, float]] = [(series[0][0], 0.0)]
    cumulative = 0.0
    for i in range(1, len(series)):
        y0, lod0 = series[i - 1]
        y1, lod1 = series[i]
        dt_days = _series_epoch_delta_days(y0, y1)
        avg_lod_ms = ((lod0 - mean_lod) + (lod1 - mean_lod)) / 2.0
        cumulative += avg_lod_ms * dt_days / 86400.0
        result.append((y1, cumulative))
    return tuple(result)


def _series_epoch_delta_days(year0: float, year1: float) -> float:
    """
    Return the exact day spacing between two series epochs when available.

    The core LOD file declares annual means at ``calendar year + 0.5``
    (mid-year). For those epochs we compute the true midpoint-to-midpoint span
    from calendar-year boundaries, so leap years propagate into the integral.

    For any other year coordinates we fall back to a uniform Julian-year scale.
    """
    jd0 = _annual_mean_midyear_jd(year0)
    jd1 = _annual_mean_midyear_jd(year1)
    if jd0 is not None and jd1 is not None:
        return jd1 - jd0
    return (year1 - year0) * JULIAN_YEAR


def _annual_mean_midyear_jd(year: float) -> float | None:
    """
    Return the JD of a calendar-year midpoint for epochs encoded as ``Y + 0.5``.

    This matches the convention documented in ``core_angular_momentum.txt``.
    Returns ``None`` when the year value does not match that annual-mean format.
    """
    whole_year = math.floor(year)
    frac = year - whole_year
    if abs(frac - 0.5) > 1e-9:
        return None
    start = julian_day(int(whole_year), 1, 1, 0.0)
    end = julian_day(int(whole_year) + 1, 1, 1, 0.0)
    return (start + end) / 2.0


@cache
def _get_core_dt_series() -> tuple[tuple[float, float], ...]:
    """Return the cached core ΔT series derived from LOD anomalies."""
    return _lod_series_to_delta_t(_load_core_series())


@cache
def _core_recent_stats() -> tuple[float, float]:
    """Return (mean, std) of the core ΔT series over the last decorrelation window."""
    series = _get_core_dt_series()
    if not series:
        return 0.0, _CORE_HISTORICAL_SIGMA
    cutoff = series[-1][0] - _CORE_DECORRELATION_YEARS
    window = [v for y, v in series if y >= cutoff]
    if len(window) < 2:
        window = [v for _, v in series]
    mean = sum(window) / len(window)
    std = statistics.stdev(window) if len(window) >= 2 else _CORE_HISTORICAL_SIGMA
    return mean, std


def core_delta_t(year: float) -> float:
    """
    Core-mantle angular momentum contribution to Delta T.

    Coverage: determined by moira/data/core_angular_momentum.txt.
    Target data: Gillet et al. (2019/2022), 1840–present.
    Outside coverage: returns 0.0 (absorbed into residual for historical era;
    replaced by the 10-year mean for future extrapolation — see delta_t_hybrid).

    Parameters
    ----------
    year : decimal year

    Returns
    -------
    ΔT contribution in seconds
    """
    series = _get_core_dt_series()
    if not series:
        return 0.0
    if year <= series[0][0] or year >= series[-1][0]:
        return 0.0
    for i in range(len(series) - 1):
        y0, v0 = series[i]
        y1, v1 = series[i + 1]
        if y0 <= year <= y1:
            frac = (year - y0) / (y1 - y0)
            return v0 + frac * (v1 - v0)
    return 0.0


def _three_year_smooth(
    years: list[float], values: list[float]
) -> tuple[list[float], list[float]]:
    """
    Apply a 3-year centred moving average to suppress AAM noise.
    Boundary points use the available neighbours only.
    """
    n = len(years)
    if n == 0:
        return [], []
    smoothed = []
    for i in range(n):
        lo = max(0, i - 1)
        hi = min(n - 1, i + 1)
        avg = sum(values[lo : hi + 1]) / (hi - lo + 1)
        smoothed.append(avg)
    return years, smoothed


def _cosine_taper(year: float) -> float:
    """
    Cosine taper window over [_RESIDUAL_TAPER_START, _RESIDUAL_TAPER_END].
    Returns 1.0 before the window, 0.0 after, cosine ramp within.
    """
    if year <= _RESIDUAL_TAPER_START:
        return 1.0
    if year >= _RESIDUAL_TAPER_END:
        return 0.0
    span = _RESIDUAL_TAPER_END - _RESIDUAL_TAPER_START
    phase = (year - _RESIDUAL_TAPER_START) / span
    return 0.5 * (1.0 + math.cos(math.pi * phase))


@cache
def _fitted_residual_spline() -> _ResidualSplineFit:
    """
    Fit a smoothing spline to IERS_measured − (secular + core + cryo) over
    the 1962–taper-end window.

    Returns the spline plus named diagnostics. The spline dependency is
    mandatory for the asserted hybrid ΔT model and will raise if scipy is
    unavailable.

    Procedure (per DELTA_T_HYBRID_MODEL.md section 3, Phase 4):
    1. Compute raw residual at each annual IERS Bulletin B point.
    2. 3-year centred pre-smooth.
    3. Apply cosine taper over 2021–2024.
    4. Fit UnivariateSpline with k=3, s=N, ext=1.
    5. Interior LOO-CV diagnostic on non-boundary annual-mean epochs.
    """
    UnivariateSpline = _require_univariate_spline()

    from moira.julian import delta_t as _iers_delta_t

    years_raw: list[float] = []
    residuals_raw: list[float] = []

    y = _RESIDUAL_FIT_START
    while y <= _RESIDUAL_TAPER_END + 0.01:
        iers_val = _iers_delta_t(y)
        model_val = secular_trend(y) + core_delta_t(y) + cryo_delta_t(y)
        years_raw.append(y)
        residuals_raw.append(iers_val - model_val)
        y += 1.0

    if len(years_raw) < 5:
        return _ResidualSplineFit(
            spline=None,
            cv_rms=_RESIDUAL_FUTURE_RMS_FALLBACK,
            in_sample_rms=_RESIDUAL_FUTURE_RMS_FALLBACK,
            knot_count=0,
        )

    _, res_smooth = _three_year_smooth(years_raw, residuals_raw)

    for i in range(len(years_raw)):
        res_smooth[i] *= _cosine_taper(years_raw[i])

    n = len(years_raw)
    s_factor = float(n)
    spline = UnivariateSpline(years_raw, res_smooth, k=3, s=s_factor, ext=1)

    knot_count = len(spline.get_knots())
    if knot_count > 20:
        s_factor = float(n) * (knot_count / 20.0)
        spline = UnivariateSpline(years_raw, res_smooth, k=3, s=s_factor, ext=1)

    loo_errors: list[float] = []
    for i in range(1, n - 1):
        ys_loo = years_raw[:i] + years_raw[i + 1 :]
        rs_loo = res_smooth[:i] + res_smooth[i + 1 :]
        if len(ys_loo) < 5:
            continue
        try:
            sp_loo = UnivariateSpline(ys_loo, rs_loo, k=3, s=s_factor, ext=1)
            loo_errors.append((res_smooth[i] - float(sp_loo(years_raw[i]))) ** 2)
        except Exception:
            pass

    if loo_errors:
        cv_rms = math.sqrt(sum(loo_errors) / len(loo_errors))
        if cv_rms > 0.4:
            s_factor *= cv_rms / 0.4
            spline = UnivariateSpline(years_raw, res_smooth, k=3, s=s_factor, ext=1)
    else:
        cv_rms = _RESIDUAL_FUTURE_RMS_FALLBACK

    in_sample_errors = [
        (res_smooth[i] - float(spline(years_raw[i]))) ** 2
        for i in range(n)
    ]
    in_sample_rms = math.sqrt(sum(in_sample_errors) / n) if in_sample_errors else _RESIDUAL_FUTURE_RMS_FALLBACK

    return _ResidualSplineFit(
        spline=spline,
        cv_rms=cv_rms,
        in_sample_rms=in_sample_rms,
        knot_count=len(spline.get_knots()),
    )


def _residual_at(year: float) -> float:
    """Evaluate the fitted residual spline at the given decimal year."""
    fit = _fitted_residual_spline()
    if fit.spline is None:
        return 0.0
    return float(fit.spline(year))


def delta_t_hybrid(year: float) -> float:
    """
    Physics-based hybrid Delta T model.

    Era routing:
      pre-1840  : delegates to SMH 2016 table (unchanged)
      1840–2026 : secular + core + cryo + IERS residual spline
      2026+     : secular + cryo trend extrapolation + core 10-year mean

    See DELTA_T_HYBRID_MODEL.md for the full architecture, era coverage
    table, and continuity constraint derivation.

    Parameters
    ----------
    year : decimal year

    Returns
    -------
    ΔT = TT − UT1 in seconds
    """
    y = float(year)
    if y < _CORE_COVERAGE_START:
        return _smh2016_lookup(y)

    base = secular_trend(y)
    core = core_delta_t(y)
    cryo = cryo_delta_t(y)

    if y <= REFERENCE_YEAR:
        return base + core + cryo + _residual_at(y)

    core_mean, _ = _core_recent_stats()
    return base + core_mean + cryo


def delta_t_hybrid_uncertainty(year: float) -> float:
    """
    ±1σ uncertainty on delta_t_hybrid(year), in seconds.

    Components are combined in quadrature (independent sources).
    Dominant term for future dates is core-mantle unpredictability.
    See DELTA_T_HYBRID_MODEL.md section 8 for the full derivation.

    Parameters
    ----------
    year : decimal year

    Returns
    -------
    ±1σ in seconds
    """
    y = float(year)
    t = (y - REFERENCE_YEAR) / 100.0

    sigma_tidal = abs(TIDAL_COEFF * t * t) * (0.003 / 25.858)

    sigma_gia = _GIA_COEFF_SIGMA * t * t

    grace_series = _load_grace_series()
    grace_end = grace_series[-1][0] if grace_series else REFERENCE_YEAR
    if y <= grace_end:
        sigma_cryo = 0.003
    else:
        sigma_cryo = _CRYO_TREND_SIGMA * (y - grace_end)

    core_series = _get_core_dt_series()
    if core_series and y <= core_series[-1][0]:
        sigma_core = _CORE_HISTORICAL_SIGMA
    else:
        _, core_std = _core_recent_stats()
        sigma_core = core_std if core_std > 0.0 else _CORE_HISTORICAL_SIGMA

    fit = _fitted_residual_spline()
    sigma_residual = fit.in_sample_rms * 0.1 if y <= REFERENCE_YEAR else fit.in_sample_rms

    return math.sqrt(
        sigma_tidal ** 2
        + sigma_gia ** 2
        + sigma_cryo ** 2
        + sigma_core ** 2
        + sigma_residual ** 2
    )
