"""
Sabian Symbols: 360 degree symbols formulated by Marc Edmund Jones and Elsie Wheeler.
Degrees are 1-indexed for each sign (1-30).
0.0 to 0.999 degrees of a sign = Degree 1.
"""

SABIAN_SYMBOLS = {
    "Aries": {
        1: "A woman has risen out of the ocean, a seal is embracing her",
        2: "A comedian entertaining the group",
        3: "A cameo shows the profile of a man that suggests the outline of his country",
        4: "Two lovers strolling through a secluded walk",
        5: "A triangle with wings",
        6: "A square brightly lighted on one side",
        7: "A man succeeds in expressing himself simultaneously in two realms",
        8: "A large hat with streamers flying, facing east",
        9: "A crystal gazer",
        10: "A teacher gives new symbolic forms to traditional images",
        11: "The president of the country",
        12: "A flock of wild geese",
        13: "An unexploded bomb reveals an unsuccessful social protest",
        14: "A serpent coiling near a man and a woman",
        15: "An Indian weaving a blanket",
        16: "Brownies dancing in the setting sun",
        17: "Two prim spinsters sitting together in silence",
        18: "An empty hammock",
        19: "The magic carpet of oriental imagery",
        20: "A young girl feeding birds in winter",
        21: "A pugilist entering the ring",
        22: "The gate to the garden of all fulfilled desires",
        23: "A woman in pastel colors carrying a heavy and valuable but veiled load",
        24: "An open window and a net curtain blowing into a cornucopia",
        25: "A double promise reveals its inner and outer meanings",
        26: "A man possessed of more gifts than he can hold",
        27: "Through imagination, a lost opportunity is regained",
        28: "A large disappointed audience",
        29: "The music of the spheres",
        30: "A duck pond and its brood"
    },
    "Taurus": {
        1: "A clear mountain stream",
        2: "An electrical storm",
        3: "Steps up to a lawn blooming with clover",
        4: "The pot of gold at the end of the rainbow",
        5: "A widow at an open grave",
        6: "A bridge being built across a gorge",
        7: "The woman of Samaria",
        8: "A sleigh without snow",
        9: "A fully decorated Christmas tree",
        10: "A Red Cross nurse",
        11: "A woman sprinkling flowers",
        12: "A young couple window shopping",
        13: "A porter carrying heavy baggage",
        14: "On the beach, children play while shellfish grope at the edge of the water",
        15: "A man with a silk hat, muffled against the cold",
        16: "An old teacher fails to interest his pupils in traditional knowledge",
        17: "A symbolical battle between 'swords' and 'torches'",
        18: "A woman airing an old bag through an open window",
        19: "A new continent rising out of the ocean",
        20: "Wisps of clouds, like wings, are streaming across the sky",
        21: "A moving finger points to significant passages in a book",
        22: "White dove flying over troubled waters",
        23: "A jewelry shop filled with valuable gems",
        24: "An Indian warrior riding fiercely, human scalps hanging from his belt",
        25: "A large well-kept public park",
        26: "A Spaniard serenading his senorita",
        27: "An old Indian woman selling beads",
        28: "A woman in middle life stands in rapt sudden realization of forgotten charms, in unexpected romance",
        29: "Two cobblers working at a table",
        30: "A peacock parading on the terrace of an old castle"
    },
    "Gemini": {
        1: "A glass-bottomed boat reveals under-sea wonders",
        2: "Santa Claus filling stockings furtively",
        3: "The garden of the Tuileries in Paris",
        4: "Holly and mistletoe bring Christmas spirit to a home",
        5: "A radical magazine",
        6: "Workmen drilling for oil",
        7: "An old-fashioned well",
        8: "Aroused strikers surround a factory",
        9: "A quiver filled with arrows",
        10: "An airplane performing a nosedive",
        11: "Newly opened lands offer the pioneer new opportunities for experience",
        12: "A Topsy saucily asserting herself",
        13: "A world famous pianist giving a concert performance",
        14: "Two people, living far apart, in telepathic communication",
        15: "Two Dutch children talking",
        16: "A woman activist in an emotional speech, dramatizing her cause",
        17: "The head of a robust youth changes into that of a mature thinker",
        18: "Two Chinese men conversing in their native tongue in an American city",
        19: "A large archaic volume reveals a traditional wisdom",
        20: "A cafeteria with an abundance of choices",
        21: "A tumultuous labor demonstration",
        22: "Dancing couples in a harvest festival",
        23: "Three fledglings in a nest high in a tree",
        24: "Children skating on ice",
        25: "A gardener trimming large palm trees",
        26: "Winter frost in the woods",
        27: "A young gypsy emerging from the woods gazes at far cities",
        28: "Through bankruptcy, society gives to an overburdened individual the opportunity to begin again",
        29: "The first mockingbird of spring",
        30: "A parade of bathing beauties before large beach crowds"
    },
    "Cancer": {
        1: "On a ship the sailors lower an old flag and raise a new one",
        2: "A man on a magic carpet observes vast vistas below him",
        3: "An explorer in fur hat and heavy garments",
        4: "A cat arguing with a mouse",
        5: "At a railroad crossing, an automobile is wrecked by a train",
        6: "Game birds feathering their nests",
        7: "Two fairies (nature spirits) dancing on a moonlit night",
        8: "A group of rabbits dressed in human clothes walk as if on parade",
        9: "A small, naked girl bends over a pond trying to catch a fish",
        10: "A large diamond in the first stages of the cutting process",
        11: "A clown caricaturing well-known personalities",
        12: "A Chinese woman nursing a baby whose aura reveals him to be the reincarnation of a great teacher",
        13: "A hand with a prominent thumb is held out for study",
        14: "A very old man facing a vast dark space to the northeast",
        15: "A group of people who have outgrown normal promises rest on a given basis",
        16: "A man studying a mandala in front of him, with the help of a very ancient book",
        17: "The seed grows into knowledge and life",
        18: "A hen scratching for her chicks",
        19: "A priest performing a marriage ceremony",
        20: "Venetian gondoliers in a serenade",
        21: "A prima donna singing",
        22: "A young woman awaiting a sailboat",
        23: "The meeting of a literary society",
        24: "A woman and two men castaways on a small island of the South Seas",
        25: "A leader of men wrapped in an invisible mantle of power",
        26: "Guests are reading in the library of a luxurious home",
        27: "A violent storm in a canyon filled with expensive homes",
        28: "An Indian girl introduces her college boyfriend to her assembled tribe",
        29: "A Greek muse weighing newborn twins in golden scales",
        30: "A Daughter of the American Revolution"
    },
    "Leo": {
        1: "Under emotional stress, blood rushes to a man's head",
        2: "An epidemic of mumps",
        3: "A middle-aged woman, her long hair flowing over her shoulders and in a braless youthful garment",
        4: "A formally dressed elderly man stands near trophies he brought back from a hunting expedition",
        5: "Rock formations tower over a deep canyon",
        6: "An old-fashioned 'conservative' woman is confronted by an up-to-date girl",
        7: "The constellations of stars in the sky",
        8: "A communist activist spreading his revolutionary ideals",
        9: "Glass blowers shape beautiful vases with their controlled breathing",
        10: "Early morning dew",
        11: "Children play on a swing hanging from the branches of a huge oak tree",
        12: "An evening lawn party of adults",
        13: "An old sea captain rocking on the porch of his cottage",
        14: "The human soul seeking opportunities for outward manifestation",
        15: "A pageant moving along a street packed with people",
        16: "Brilliant sunshine just after a storm",
        17: "Volunteer church choir making social contacts",
        18: "A chemist conducts an experiment for his students",
        19: "A houseboat party",
        20: "American Indians perform a ritual to the sun",
        21: "Intoxicated chickens dizzily flap their wings trying to fly",
        22: "A carrier pigeon fulfilling its mission",
        23: "A bareback rider in a circus displays her dangerous skill",
        24: "Totally concentrated upon inner spiritual attainment, a man is sitting in a state of complete neglect of his body",
        25: "A large camel is seen crossing a vast and forbidding desert",
        26: "After a heavy storm, a rainbow",
        27: "Daybreak - the luminescence of dawn in the eastern sky",
        28: "Many little birds on a limb of a large tree",
        29: "A mermaid emerges from the ocean waves ready for rebirth in human form",
        30: "An unsealed letter"
    },
    "Virgo": {
        1: "In a portrait, the significant features of a man's head are artistically emphasized",
        2: "A large white cross, dominating the landscape, stands alone",
        3: "Two guardian angels bringing protection",
        4: "Black and white children playing together happily",
        5: "A man becoming aware of nature spirits and normally unseen spiritual agencies",
        6: "A merry-go-round",
        7: "A harem",
        8: "A girl takes her first dancing instruction",
        9: "A expressionist painter making a futuristic drawing",
        10: "Two heads looking out and beyond the shadows",
        11: "A boy molded in his mother's aspirations for him",
        12: "A bride with her veil snatched away",
        13: "A powerful statesman overcomes a state of political hysteria",
        14: "A family tree",
        15: "A fine lace ornamental handkerchief",
        16: "Children crowd around the orangutan cage in the zoo",
        17: "A volcanic eruption",
        18: "An ouija board",
        19: "A swimming race",
        20: "A caravan of cars headed for promised lands",
        21: "A girls' basketball team",
        22: "A royal coat of arms enriched with precious stones",
        23: "A lion tamer rushes fearlessly into the circus arena",
        24: "Mary and her little lamb",
        25: "A flag at half-mast in front of a public building",
        26: "A boy with a censer serves near the priest at the altar",
        27: "Aristocratic elderly ladies drinking afternoon tea in a wealthy home",
        28: "A bald-headed man who has seized power",
        29: "A man gaining secret knowledge from an ancient scroll he is reading",
        30: "Totally intent upon completing an immediate task, a man is deaf to any allurement"
    },
    "Libra": {
        1: "A butterfly preserved and made perfect with a dart through it",
        2: "The light of the sixth race transmuted to the seventh",
        3: "The dawn of a new day reveals everything changed",
        4: "A group of young people sit in spiritual communion around a campfire",
        5: "A man teaching the true inner knowledge of the new world to his students",
        6: "A man watches his ideals taking a concrete form before his inner vision",
        7: "A woman feeding chickens and protecting them from the hawks",
        8: "A blazing fireplace in a deserted home",
        9: "Three old masters hanging in a special room in an art gallery",
        10: "A canoe approaching safety through dangerous waters",
        11: "A professor peering over his glasses at his students",
        12: "Miners are emerging from a deep coal mine",
        13: "Children blowing soap bubbles",
        14: "In the heat of the noon, a man takes a siesta",
        15: "Circular paths",
        16: "After a storm, a boat landing stands in need of reconstruction",
        17: "A retired sea captain watches ships entering and leaving the harbor",
        18: "Two men placed under arrest",
        19: "A gang of robbers in hiding",
        20: "A Jewish rabbi performing his duties",
        21: "A crowd upon a beach",
        22: "A child giving birds a drink at a fountain",
        23: "Chanticleer's voice heralds the rising sun with enthusiastic tones",
        24: "A third wing on the left side of a butterfly",
        25: "The sight of an autumn leaf brings to a pilgrim the sudden revelation of the mystery of life and death",
        26: "An eagle and a large white dove turning one into the other",
        27: "An airplane sails, high in the clear sky",
        28: "A man becoming aware of spiritual forces surrounding and assisting him",
        29: "Humanity's vast and enduring effort to reach for knowledge transferable from generation to generation",
        30: "Three mounds of knowledge on a philosopher's head"
    },
    "Scorpio": {
        1: "A sightseeing bus filled with tourists",
        2: "A broken bottle and spilled perfume",
        3: "Neighbors help in a house-raising party in a small village",
        4: "A youth holding a lighted candle in a devotional ritual",
        5: "A massive, rocky shore resists the pounding of the sea",
        6: "The gold rush tears men away from their native soil",
        7: "Deep-sea divers",
        8: "The moon shining across a lake",
        9: "A dentist at work",
        10: "A fellowship supper reunites old comrades",
        11: "A drowning man is being rescued",
        12: "An official embassy ball",
        13: "An inventor performs a laboratory experiment",
        14: "Telephone linemen at work installing new connections",
        15: "Children playing around five mounds of sand",
        16: "A girl's face breaking into a smile",
        17: "A woman, filled with her own spirit, is father of her own child",
        18: "A path through woods brilliant with multicolored splendor",
        19: "A parrot listening and then talking, repeats a conversation he has overheard",
        20: "A woman drawing aside two dark curtains that closed the entrance to a sacred pathway",
        21: "Obeying his conscience, a soldier resists orders",
        22: "Hunters shooting wild ducks",
        23: "A rabbit metamorphoses into a nature spirit",
        24: "Crowds coming down the mountain to listen to one inspired man",
        25: "An x-ray photograph",
        26: "American Indians making camp after moving into a new territory",
        27: "A military band marches noisily on through the city streets",
        28: "The king of the fairies approaching his domain",
        29: "An Indian squaw pleading to the chief for the lives of her children",
        30: "Children in Halloween costumes indulging in various pranks"
    },
    "Sagittarius": {
        1: "Retired army veterans gather to reawaken old memories",
        2: "White-capped waves display the power of wind over sea",
        3: "Two men playing chess",
        4: "A little child learning to walk",
        5: "An old owl sits alone on the branch of a large tree",
        6: "A game of cricket",
        7: "Cupid knocks at the door of a human heart",
        8: "Within the depths of the earth new elements are being formed",
        9: "A mother leads her small child step by step up a steep stairway",
        10: "A theatrical representation of a golden-haired goddess of opportunity",
        11: "In the left section of an archaic temple, a lamp burns in a container shaped like a human body",
        12: "A flag that turns into an eagle that crows",
        13: "A widow's past is brought to light",
        14: "The Pyramids and the Sphinx",
        15: "The ground hog looking for its shadow on Groundhog Day",
        16: "Sea gulls fly around a ship looking for food",
        17: "An Easter sunrise service draws a large crowd",
        18: "Children playing on the beach, their heads protected by sunbonnets",
        19: "Pelicans menaced by the behavior and refuse of men seek safer areas for bringing up their young",
        20: "In winter people are cutting ice from a frozen pond, for use in summer",
        21: "A child and a dog wearing borrowed eyeglasses",
        22: "A Chinese laundry",
        23: "A group of immigrants fulfilling the requirements for entering a new country",
        24: "A bluebird perched on the door of a cottage",
        25: "A chubby boy on a hobbyhorse",
        26: "A flag-bearer in a battle",
        27: "A sculptor at his work",
        28: "An old bridge over a beautiful stream in constant use",
        29: "A fat boy mowing the lawn",
        30: "The Pope blessing the faithful"
    },
    "Capricorn": {
        1: "An Indian chief claims power from the assembled tribe",
        2: "Three rose windows in a Gothic church, one damaged by war",
        3: "The human soul, in its eagerness for new experiences, seeks embodiment",
        4: "A group of people outfitting a large canoe at the start of a journey by water",
        5: "Indians on the warpath. While some men row a well-filled canoe, others in it perform a war dance",
        6: "Ten logs lie under an archway leading to darker woods",
        7: "A veiled prophet speaks, seized by the power of a god",
        8: "In a sunlit home domesticated birds sing joyously",
        9: "An angel carrying a harp",
        10: "An albatross feeding from the hand of a sailor",
        11: "A large group of pheasant on a private estate",
        12: "A student of nature lecturing revealing little-known aspects of life",
        13: "A fire worshiper meditates on the ultimate realities of existence",
        14: "An ancient bas-relief carved in granite remains a witness to a long-forgotten culture",
        15: "In a hospital, the children's ward is filled with toys",
        16: "School grounds filled with boys and girls in gymnasium suits",
        17: "A repressed woman finds a psychological release in nudism",
        18: "The Union Jack flies from a British warship",
        19: "A five-year-old child carrying a bag filled with groceries",
        20: "A hidden choir singing during a religious service",
        21: "A relay race",
        22: "A general accepting defeat gracefully",
        23: "A soldier receiving two awards for bravery in combat",
        24: "A woman entering a convent",
        25: "An Oriental rug dealer in a store full of precious ornamental rugs",
        26: "A nature sprite dancing in the mist of a waterfall",
        27: "A mountain pilgrimage",
        28: "A large aviary",
        29: "A woman reading tea leaves",
        30: "A secret meeting of men responsible for executive decisions in world affairs"
    },
    "Aquarius": {
        1: "An old adobe mission in California",
        2: "An unexpected thunderstorm",
        3: "A deserter from the navy stands suddenly aware of a freedom that is not his true identity",
        4: "A Hindu yogi demonstrates his healing powers",
        5: "A council of ancestors is seen implementing the efforts of a young leader",
        6: "A masked figure performs ritualistic acts in a mystery play",
        7: "A child born out of an eggshell",
        8: "Beautifully gowned wax figures on display",
        9: "A flag is seen turning into an eagle",
        10: "A man who had for a time become the embodiment of an ideal is made to realize that as a person he is not this ideal",
        11: "During a silent hour, a man receives a new inspiration which may change his life",
        12: "On a vast staircase stand people of different types, graduated upward",
        13: "A barometer",
        14: "A train entering a tunnel",
        15: "Two lovebirds sitting on a fence and singing happily",
        16: "A big businessman at his desk",
        17: "A watchdog standing guard, protecting his master and his possessions",
        18: "A man's secret motives are being publicly unmasked",
        19: "A forest fire finally quenched",
        20: "A large white dove bearing a message",
        21: "A woman disappointed and disillusioned, courageously facing a seemingly empty life",
        22: "A rug placed on a floor for children to play on",
        23: "A big bear sitting down and waving all its paws",
        24: "A man turning his back on his passions teaches deep wisdom from his experience",
        25: "A butterfly with the right wing more perfectly formed",
        26: "A garage man testing a car's battery with a hydrometer",
        27: "An ancient pottery bowl filled with fresh violets",
        28: "A tree felled and sawed to ensure a supply of wood for the winter",
        29: "A butterfly emerging from a chrysalis",
        30: "Moon-lit fields, once Babylon, are blooming white"
    },
    "Pisces": {
        1: "A large public market",
        2: "A squirrel hiding from hunters",
        3: "A petrified forest",
        4: "Heavy car traffic on a narrow isthmus linking two seaside resorts",
        5: "A church bazaar",
        6: "A parade of army officers in full dress",
        7: "Illuminated by a shaft of light, a large cross lies on rocks surrounded by sea",
        8: "A girl blowing a bugle",
        9: "A jockey spurs his horse, intent on outdistancing his rivals",
        10: "An aviator in the clouds",
        11: "Men traveling a narrow path, seeking illumination",
        12: "In the sanctuary of an occult brotherhood, newly initiated members are being examined and their character tested",
        13: "An ancient sword, used in many battles, is displayed in a museum",
        14: "A lady wrapped in a large stole of fox fur",
        15: "An officer preparing to drill his men",
        16: "In a quiet moment, a creative individual experiences the flow of inspiration",
        17: "An Easter promenade",
        18: "In a gigantic tent, villagers witness a spectacular performance",
        19: "A master instructing his disciple",
        20: "A table set for an evening meal",
        21: "A little white lamb, a child and a Chinese servant",
        22: "A prophet bringing down the new law from the mountain",
        23: "A 'materializing' medium giving a seance",
        24: "The far-flung, inhabited island",
        25: "A religious organization succeeds in overcoming the corrupting influence of perverted practices and materialized ideals",
        26: "Watching the very thin moon crescent appearing at sunset, different people realize that the time has come to go ahead with their different projects",
        27: "The harvest moon illuminates a clear autumnal sky",
        28: "A fertile garden under the full moon reveals a variety of full-grown vegetables",
        29: "Light breaking into many colors as it passes through a prism",
        30: "A majestic rock formation resembling a face is idealized by a boy who takes it as his ideal of greatness, and as he grows up, begins to look like it"
    }
}
