"""
moira.vedic — Vedic astrology surface.

Builds on ``moira.essentials`` and collects every Vedic-domain subsystem
into a single, coherent import surface: panchanga, sidereal/ayanamsa,
nakshatra, varga (divisional charts), Vedic dignities, Vimshottari and
alternate dasha systems, Jaimini karakas and extended techniques, yogas,
avasthas, Muhurta, upagrahas, Sade Sati, Gochara, Ashtakavarga, and Shadbala.

This module does not include the full Western classical surface
(Arabic lots, Firdaria, Zodiacal Releasing, Huber, etc.). For that,
use ``moira.classical``. For the complete surface, use ``moira.facade``.

Usage
-----
    from moira.vedic import *

    m = Moira()
    chart = m.chart(datetime(1985, 3, 21, 6, 0, tzinfo=timezone.utc))

    # Ayanamsa and sidereal positions
    ayan = ayanamsa(chart.jd_ut, Ayanamsa.LAHIRI)
    naks = all_nakshatras_at(chart.longitudes(), chart.jd_ut)

    # Panchanga for the moment
    pg = panchanga_at(
        chart.planets['Sun'].longitude,
        chart.planets['Moon'].longitude,
        chart.jd_ut,
    )

    # Vedic dignities
    dignities = {b: vedic_dignity(b, lon) for b, lon in chart.longitudes().items()}

    # Vimshottari dasha
    periods = vimshottari(chart.planets['Moon'].longitude, chart.jd_ut)

    # Shadbala convenience method
    houses = m.houses(
        datetime(1985, 3, 21, 6, 0, tzinfo=timezone.utc),
        latitude=28.6,
        longitude=77.2,
    )
    strength = m.shadbala_for_chart(chart, houses)

Next step
---------
For transits, progressions, synastry, eclipses, and returns, use
``moira.predictive``. The core Vedic return entry points ``varshaphal()``
and ``varshaphal_chart()`` are also re-exported here.

For the complete surface, use ``moira.facade``.
"""

from __future__ import annotations

# ── Everything from essentials ───────────────────────────────────────────
from .essentials import *  # noqa: F401,F403
from .essentials import __all__ as _essentials_all

# ── Sidereal / Ayanamsa (full) ───────────────────────────────────────────
from .sidereal import (
    UserDefinedAyanamsa,
    NakshatraPosition,
    nakshatra_of,
    all_nakshatras_at,
)

# ── Panchanga ────────────────────────────────────────────────────────────
from .lunar_month import (
    LunarMonthSystem, LunarMonthPolicy, CalendarBoundary, LunarMonthLabel,
    LunarLunation, LunarMonthProvenance, LunarMonthResult, lunar_month_at,
)
from .daily_panchanga import (
    PanchangaSunriseDefinition, DailyPanchangaPolicy, PanchangaMoment,
    PanchangaSolarDate, PanchangaLimbInterval, PanchangaLimbDay,
    DailyPanchangaProvenance, DailyPanchangaResult, daily_panchanga,
)
from .panchanga import (
    TithiPaksha,
    YogaClass,
    KaranaType,
    VaraLordType,
    PanchangaPolicy,
    TITHI_NAMES,
    YOGA_NAMES,
    KARANA_NAMES,
    VARA_LORDS,
    VARA_NAMES,
    RASHI_NAMES,
    PanchangaElement,
    PanchangaResult,
    SankrantiResult,
    TithiConditionProfile,
    PanchangaProfile,
    panchanga_at,
    sankranti_at,
    tithi_condition_profile,
    panchanga_profile,
    validate_panchanga_output,
)

from .pancha_pakshi import (
    PanchaPakshiActivity,
    PanchaPakshiAdmissionStatus,
    PanchaPakshiAstronomicalPaksha,
    PanchaPakshiAstronomicalPakshaInference,
    PanchaPakshiAstronomicalPakshaInferencePolicy,
    PanchaPakshiBird,
    PanchaPakshiCivilTimeSookshmaRoutingPolicy,
    PanchaPakshiCivilTimeSookshmaSelection,
    PanchaPakshiCapability,
    PanchaPakshiConflictWitness,
    PanchaPakshiCurrentCellSelectionStatus,
    PanchaPakshiDataError,
    PanchaPakshiDirectedRelationship,
    PanchaPakshiError,
    PanchaPakshiFixedClockCell,
    PanchaPakshiFixedClockCurrentCellSelection,
    PanchaPakshiFixedClockCurrentCellSelectionPolicy,
    PanchaPakshiFixedClockMaterialization,
    PanchaPakshiFixedClockMaterializationPolicy,
    PanchaPakshiFirstEatBirdMapping,
    PanchaPakshiHalf,
    PanchaPakshiInitialVowelIdentity,
    PanchaPakshiLocalSolarContext,
    PanchaPakshiLocalSolarContextPolicy,
    PanchaPakshiMaterializedCellRelation,
    PanchaPakshiNakshatraBirdMapping,
    PanchaPakshiNatalMoonIdentity,
    PanchaPakshiNatalMoonIdentityPolicy,
    PanchaPakshiOmission,
    PanchaPakshiPaduBirdMapping,
    PanchaPakshiPaksha,
    PanchaPakshiProfileDescriptor,
    PanchaPakshiProfileInfo,
    PanchaPakshiProvenance,
    PanchaPakshiRelation,
    PanchaPakshiSchedule,
    PanchaPakshiScheduleCell,
    PanchaPakshiSolarProportionalCell,
    PanchaPakshiSolarProportionalCurrentCellSelection,
    PanchaPakshiSolarProportionalCurrentCellSelectionPolicy,
    PanchaPakshiSolarProportionalMaterialization,
    PanchaPakshiSolarProportionalMaterializationPolicy,
    PanchaPakshiSolarBoundaryRelation,
    PanchaPakshiSource,
    PanchaPakshiSourceLocator,
    PanchaPakshiScheduleSookshmaCompositionPolicy,
    PanchaPakshiScheduleSookshmaSelection,
    PanchaPakshiSookshmaInterval,
    PanchaPakshiSookshmaSelection,
    PanchaPakshiSookshmaSelectorPolicy,
    PanchaPakshiSookshmaSelectorPolicyId,
    PanchaPakshiSookshmaTimingPolicyId,
    PanchaPakshiUromarisiConstitutionStatus,
    PanchaPakshiWeekday,
    available_pancha_pakshi_profiles,
    pancha_pakshi_astronomical_paksha_at,
    pancha_pakshi_civil_time_sookshma_selection_at,
    pancha_pakshi_directed_relationship,
    pancha_pakshi_fixed_clock_current_cell_at,
    pancha_pakshi_fixed_clock_materialization_at,
    pancha_pakshi_first_eat_bird_mapping,
    pancha_pakshi_identity_from_initial_vowel,
    pancha_pakshi_local_solar_context_at,
    pancha_pakshi_nakshatra_bird_mapping,
    pancha_pakshi_natal_moon_identity_at,
    pancha_pakshi_padu_bird_mapping,
    pancha_pakshi_profile_info,
    pancha_pakshi_schedule,
    pancha_pakshi_schedule_sookshma_temporal_selection,
    pancha_pakshi_sookshma_temporal_selection,
    pancha_pakshi_solar_proportional_current_cell_at,
    pancha_pakshi_solar_proportional_materialization_at,
    pancha_pakshi_uromarisi_constitution_status,
)

# ── Vedic Dignities ──────────────────────────────────────────────────────
from .vedic_dignities import (
    VedicDignityRank,
    CompoundRelationship,
    DignityTier,
    EXALTATION_SIGN,
    EXALTATION_DEGREE,
    DEBILITATION_SIGN,
    MULATRIKONA_SIGN,
    MULATRIKONA_START,
    MULATRIKONA_END,
    OWN_SIGNS,
    NATURAL_FRIENDS,
    NATURAL_NEUTRALS,
    NATURAL_ENEMIES,
    VedicDignityResult,
    PlanetaryRelationship,
    VedicDignityPolicy,
    DignityConditionProfile,
    ChartDignityProfile,
    vedic_dignity,
    planetary_relationships,
    dignity_condition_profile,
    chart_dignity_profile,
    validate_dignity_output,
)

# ── Varga (divisional charts) ────────────────────────────────────────────
from .varga import (
    D60Method, D60SignResult, d60_sign,
    VargaPoint,
    calculate_varga,
    navamsa,
    saptamsa,
    dashamansa,
    dwadashamsa,
    trimshamsa,
    hora,
    chaturthamsha,
    shashthamsha,
    ashtamsha,
    shodashamsha,
    vimshamsha,
    chaturvimshamsha,
    saptavimshamsha,
    khavedamsha,
    akshavedamsha,
    shashtiamsha,
)

# ── Vimshottari Dasha ────────────────────────────────────────────────────
from .dasha import (
    VIMSHOTTARI_YEARS,
    VIMSHOTTARI_SEQUENCE,
    VIMSHOTTARI_TOTAL,
    VIMSHOTTARI_YEAR_BASIS,
    VIMSHOTTARI_LEVEL_NAMES,
    DashaLordType,
    VimshottariYearPolicy,
    VimshottariAyanamsaPolicy,
    VimshottariComputationPolicy,
    DEFAULT_VIMSHOTTARI_POLICY,
    DashaPeriod,
    DashaActiveLine,
    DashaConditionProfile,
    DashaSequenceProfile,
    DashaLordPair,
    vimshottari,
    current_dasha,
    dasha_balance,
    dasha_active_line,
    dasha_condition_profile,
    dasha_sequence_profile,
    dasha_lord_pair,
    validate_vimshottari_output,
)

# ── Alternate Dasha Systems (Ashtottari, Yogini) ─────────────────────────
from .dasha_systems import (
    AlternateDashaSystem,
    ASHTOTTARI_YEARS,
    ASHTOTTARI_SEQUENCE,
    ASHTOTTARI_NAKSHATRA_LORD,
    ASHTOTTARI_TOTAL,
    YOGINI_YEARS,
    YOGINI_SEQUENCE,
    YOGINI_PLANETS,
    YOGINI_TOTAL,
    AlternateDashaPeriod,
    AshtottariPolicy,
    YoginiPolicy,
    AlternatePeriodProfile,
    AlternateDashaSequenceProfile,
    ashtottari,
    yogini_dasha,
    alternate_period_profile,
    alternate_sequence_profile,
    validate_alternate_dasha_output,
)

# ── Jaimini Karakas ──────────────────────────────────────────────────────
from .jaimini import (
    KarakaRole,
    KarakaPlanetType,
    JaiminiPolicy,
    KARAKA_NAMES_7,
    KARAKA_NAMES_8,
    KarakaAssignment,
    JaiminiKarakaResult,
    KarakaConditionProfile,
    JaiminiChartProfile,
    KarakaPair,
    jaimini_karakas,
    atmakaraka,
    karaka_condition_profile,
    jaimini_chart_profile,
    karaka_pair,
    validate_jaimini_output,
)

# ── Ashtakavarga ─────────────────────────────────────────────────────────
from .ashtakavarga import (
    RekhaTier,
    AshtakavargaPolicy,
    REKHA_TABLES,
    BhinnashtakavargaResult,
    AshtakavargaResult,
    SignStrengthProfile,
    AshtakavargaChartProfile,
    bhinnashtakavarga,
    ashtakavarga,
    transit_strength,
    sign_strength_profile,
    ashtakavarga_chart_profile,
    validate_ashtakavarga_output,
)

# ── Gochara Phala ────────────────────────────────────────────────────────
from .gochara import (
    GOCHARA_PROFILE, GOCHARA_PLANETS, GocharaVedhaStatus,
    GocharaPosition, GocharaVedhaWitness, GocharaPlanetResult,
    GocharaResult, gochara_from_positions,
    DEFAULT_GOCHARA_POLICY, GocharaSourceProfile, GocharaVedhaMode,
    GocharaCompleteness, GocharaBavMode, GocharaAdmissionStatus,
    GocharaDoctrineOption, GocharaPolicy, gochara_doctrine_options,
    GocharaBaselineClass, GocharaBavAvailability, GocharaVedhaRelationClass,
    GocharaLocalCondition, GocharaLocalProfile, GocharaChartSummary,
    GocharaNetworkNode, GocharaVedhaNetwork, GocharaSubsystemProfile,
    gochara_local_profiles, gochara_subsystem_profile,
)
from .gochara_dated import (
    GocharaNatalBavMode, GocharaDatePolicy, DEFAULT_GOCHARA_DATE_POLICY,
    GocharaBirthLocation, GocharaDatedPosition, GocharaEpoch, GocharaDateResult,
    GocharaResourceError, GocharaCoverageError, gochara_at, gochara_for_datetimes,
)

# ── Shadbala ─────────────────────────────────────────────────────────────
from .shadbala import (
    NAISARGIKA_BALA,
    REQUIRED_RUPAS,
    MEAN_DAILY_MOTION,
    ShadbalaTier,
    SthanaBala,
    KalaBala,
    PlanetShadbala,
    ShadbalaResult,
    ShadbalaPolicy,
    ShadbalaContext,
    ShadbalaContextError,
    derive_shadbala_context,
    SaptavargajaEntry,
    saptavargaja_breakdown,
    WarResolution,

    ShadbalaConditionProfile,
    ShadbalaChartProfile,
    sthana_bala,
    dig_bala,
    kala_bala,
    chesta_bala,
    drig_bala,
    shadbala,
    hora_lord_at,
    shadbala_condition_profile,
    shadbala_chart_profile,
    validate_shadbala_output,
)

from .transits import varshaphal, varshaphal_chart
from .varshaphal import (
    TajikaPanchavargiStrength,
    TajikaKalaBala,
    TajikaChestaBala,
    TajikaDrigBala,
    TajikaShadbalaProfile,
    VarshaphalActorJudgement,
    VarshaphalSahamJudgement,
    VarshaphalSahamPriority,
    VarsheshaCandidate,
    VarsheshaResult,
    VarshaphalJudgementProfile,
    VarshaphalYearJudgement,
    VarshaphalTopicJudgement,
    VarshaphalTopicWindow,
    VarshaphalYearSummary,
    TajikaAspectPolicy,
    TajikaAspect,
    TajikaYoga,
    VarshaphalSahamDefinition,
    VarshaphalSaham,
    MunthaConditionProfile,
    MuddaDashaPeriod,
    MuddaDasha,
    MuddaDashaActivation,
    TasiraPeriod,
    TasiraDasha,
    MuddaPeriodJudgement,
    MuddaPeriodResultProfile,
    VarshaphalChart,
    muntha,
    mudda_dasha,
    active_mudda_dasha,
    tasira_periods,
    active_tasira_period,
    mudda_period_judgement,
    tajika_panchavargi_strength,
    tajika_shadbala_profile,
    tajika_aspects,
    tajika_yogas,
    varshesha,
    varshaphal_judgement_profile,
    varshaphal_year_judgement,
    varshaphal_topic_judgements,
    varshaphal_topic_windows,
    varshaphal_year_summary,
    muntha_condition_profile,
    varshaphal_sahams,
    build_varshaphal_chart,
)


# ── Build __all__ ────────────────────────────────────────────────────────

# Existing curated varga products.
from .varga import (
    VIMSHOPAKA_GROUPS,
    VARGA_VISHVA,
    VimshopakaVargaEntry,
    VimshopakaBala,
    varga_sign_index,
    vimshopaka_bala,
    vimshopaka_all,
    is_vargottama,
    vargottama_planets,
)

# Existing curated ashtakavarga products.
from .ashtakavarga import (
    KAKSHYA_LORDS,
    RASIMANA,
    GRAHAMANA,
    KakshyaTransit,
    ShodhyaPinda,
    kakshya_transit,
    shodhya_pinda,
)

# Existing curated shadbala products.
from .shadbala import (
    BhavaBala,
    BhavaBalaResult,
    bhava_bala,
    bhava_dig_bala,
    bhava_drishti_bala,
)

# Existing curated yogas products.
from .yogas import (
    YogaPolicy,
    YogaCondition,
    YogaResult,
    YogaChartResult,
    benefic_malefic_classification,
    pancha_mahapurusha_yogas,
    chandra_yogas,
    surya_yogas,
    nabhasa_yogas,
    raja_yogas,
    dhana_yogas,
    evaluate_yogas,
)

# Existing curated avasthas products.
from .avasthas import (
    AvasthaPolicy,
    SayanadiAvastha,
    SayanadiPolicy,
    SayanadiName,
    SayanadiGhati,
    SayanadiContext,
    SayanadiTrace,
    SayanadiEffectProvenance,
    sayanadi_avastha,
    sayanadi_ghati_from_elapsed,
    BaladiAvastha,
    JagradadiAvastha,
    DeeptadiAvastha,
    LajjitadiState,
    LajjitadiAvasthas,
    PlanetAvasthas,
    AvasthaChartResult,
    baladi_avastha,
    jagradadi_avastha,
    deeptadi_avastha,
    lajjitadi_avasthas,
    evaluate_avasthas,
)
from .sayanadi_dated import (
    SayanadiBirthPolicy,
    SayanadiSunriseBracket,
    AvasthaBirthResult,
    SayanadiResourceError,
    SayanadiCoverageError,
    avasthas_for_datetime,
)

# Existing curated jaimini_extended products.
from .jaimini_extended import (
    JaiminiExtendedPolicy,
    rasi_aspects,
    rasi_drishti_of,
    ArudhaPada,
    ArudhaResult,
    arudha_padas,
    ArgalaHouse,
    ArgalaResult,
    argala,
    Karakamsa,
    karakamsa,
    CharaDashaPeriod,
    CharaDashaResult,
    CharaDashaComputation,
    chara_dasha,
)

# Existing curated muhurta products.
from .muhurta import (
    MuhurtaPolicy,
    MuhurtaClassification,
    MuhurtaScore,
    classify_muhurta,
    score_muhurta,
    TARA_NAMES,
    TaraBala,
    tara_bala,
    ChandraBala,
    chandra_bala,
    PersonalMuhurtaScore,
    personal_muhurta_score,
)
from .muhurta_marriage import (
    MarriageElectionPolicy,
    MarriagePlanet,
    MarriageExtent,
    MarriageTimeSpan,
    MarriageSolarContext,
    MarriageIngress,
    MarriageIngressHistory,
    MarriageStarPassage,
    MarriageHistoricalSkySpan,
    MarriageHistoricalLongitude,
    MarriageHistoricalSkyBand,
    MarriageMoon28Passage,
    MarriageStarHistory,
    MarriageYogaEnding,
    MarriageElectionEvidence,
    MarriageParticipant,
    MarriagePersonalContext,
    MarriageMeasure,
    MarriageException,
    MarriageFinding,
    MarriageDecision,
    MarriageElectionAssessment,
    assess_marriage_election,
    marriage_election_catalogue,
)
from .muhurta_marriage_visibility import (
    MarriageTimeDegrees,
    MarriageVisibilitySample,
    MarriageVisibilityEvent,
    MarriageApparitionContext,
    MarriageAvailability,
    marriage_time_degrees,
    marriage_planet_availability,
)
from .muhurta_marriage_dated import (
    MarriageSearchLimits,
    MarriageSearchBudgetError,
    MarriageSearchReceipt,
    MarriageElectionSnapshot,
    marriage_election_for_datetime,
)
from ._muhurta_marriage_windows import (
    MarriageEvidencePart, MarriageWindowWitness, MarriageElectionCell,
    MarriageElectionWindows, marriage_election_windows,
)
from .muhurta_lagna import (
    MuhurtaLagnaPolicy,
    LagnaPlanet,
    LagnaRuleEvidence,
    LagnaPlacementContribution,
    LagnaPlacementScore,
    LagnaRestriction,
    MuhurtaLagnaAssessment,
    evaluate_muhurta_lagna_strength,
    muhurta_lagna_catalogue,
)
from .muhurta_lagna_dated import MuhurtaLagnaSnapshot, muhurta_lagna_for_datetime
from .muhurta_dosha import (
    MuhurtaDoshaPolicy,
    DoshaPhaseSpan,
    MuhurtaDoshaInputs,
    DoshaWitness,
    DoshaPredicate,
    PariharaEvidence,
    MuhurtaDoshaFinding,
    MuhurtaDoshaAssessment,
    DoshaCatalogueEntry,
    MuhurtaDoshaCatalogue,
    MuhurtaDoshaCell,
    MuhurtaDoshaDay,
    muhurta_dosha_catalogue,
    detect_muhurta_doshas,
    muhurta_doshas_for_date,
)
from .panchanga_shuddhi import (
    PanchangaShuddhiPolicy,
    ShuddhiBoundary,
    ShuddhiInterval,
    ShuddhiFinding,
    ShuddhiInputs,
    ShuddhiValues,
    PanchangaShuddhiAssessment,
    ShuddhiCatalogueEntry,
    ShuddhiCatalogue,
    PanchakaRahita,
    ShuddhiCell,
    PanchangaShuddhiDay,
    panchanga_shuddhi_catalogue,
    panchanga_shuddhi_from_longitudes,
    panchaka_rahita,
    panchanga_shuddhi_for_date,
)
from .special_muhurta import (
    SpecialMuhurtaPolicy, SpecialMuhurtaBoundary, SpecialMuhurtaWindow,
    SpecialMuhurtaResult, SpecialMuhurtaSolarResult, MuhurtaYogaMatch,
    MuhurtaYogaSnapshot, SpecialMuhurtaDay, special_muhurta_from_solar_times,
    muhurta_yogas_from_longitudes, special_muhurta_for_date,
)
from .named_muhurta import (
    NamedMuhurtaPolicy, NamedMuhurtaAnchor, NamedMuhurtaInterval,
    NamedMuhurtaResult, NamedMuhurtaDay, named_muhurta_from_solar_times, named_muhurta_for_date,
)
from .muhurta_search import (
    MuhurtaSearchPolicy, MuhurtaMomentScore, MuhurtaSearchWindow, MuhurtaSearchResult,
    MuhurtaResourceError, MuhurtaCoverageError, muhurta_score_for_chart, find_muhurta_windows,
)

# Existing curated upagrahas products.
from .upagrahas import (
    UpagrahaPolicy,
    SunBasedUpagrahas,
    KalavelaUpagraha,
    KalavelaResult,
    sun_based_upagrahas,
    kalavela_upagrahas,
)

# Existing curated sade_sati products.
from .sade_sati import (
    SADE_SATI_PHASES,
    SadeSatiStatus,
    SadeSatiWindow,
    SadeSatiResult,
    SadeSatiBudgetError,
    DEFAULT_SADE_SATI_EVALUATIONS,
    MAX_SADE_SATI_EVALUATIONS,

    sade_sati_status,
    sade_sati_windows,
)

_VEDIC_OWN: list[str] = [
    "MuhurtaLagnaPolicy",
    "LagnaPlanet",
    "LagnaRuleEvidence",
    "LagnaPlacementContribution",
    "LagnaPlacementScore",
    "LagnaRestriction",
    "MuhurtaLagnaAssessment",
    "MarriageElectionPolicy",
    "MarriagePlanet",
    "MarriageExtent",
    "MarriageTimeSpan",
    "MarriageSolarContext",
    "MarriageIngress",
    "MarriageIngressHistory",
    "MarriageStarPassage",
    "MarriageHistoricalSkySpan",
    "MarriageHistoricalLongitude",
    "MarriageHistoricalSkyBand",
    "MarriageMoon28Passage",
    "MarriageStarHistory",
    "MarriageYogaEnding",
    "MarriageElectionEvidence",
    "MarriageParticipant",
    "MarriagePersonalContext",
    "MarriageMeasure",
    "MarriageException",
    "MarriageFinding",
    "MarriageDecision",
    "MarriageElectionAssessment",
    "assess_marriage_election",
    "marriage_election_catalogue",
    "MarriageTimeDegrees",
    "MarriageVisibilitySample",
    "MarriageVisibilityEvent",
    "MarriageApparitionContext",
    "MarriageAvailability",
    "marriage_time_degrees",
    "marriage_planet_availability",
    "MarriageSearchLimits",
    "MarriageSearchBudgetError",
    "MarriageSearchReceipt",
    "MarriageElectionSnapshot",
    "marriage_election_for_datetime",
    "MarriageEvidencePart", "MarriageWindowWitness", "MarriageElectionCell",
    "MarriageElectionWindows", "marriage_election_windows",
    "evaluate_muhurta_lagna_strength",
    "muhurta_lagna_catalogue",
    "MuhurtaLagnaSnapshot",
    "muhurta_lagna_for_datetime",
    "MuhurtaDoshaPolicy",
    "DoshaPhaseSpan",
    "MuhurtaDoshaInputs",
    "DoshaWitness",
    "DoshaPredicate",
    "PariharaEvidence",
    "MuhurtaDoshaFinding",
    "MuhurtaDoshaAssessment",
    "DoshaCatalogueEntry",
    "MuhurtaDoshaCatalogue",
    "MuhurtaDoshaCell",
    "MuhurtaDoshaDay",
    "muhurta_dosha_catalogue",
    "detect_muhurta_doshas",
    "muhurta_doshas_for_date",
    "D60Method", "D60SignResult", "d60_sign",
    # Sidereal (extended)
    "UserDefinedAyanamsa",
    "NakshatraPosition",
    "nakshatra_of",
    "all_nakshatras_at",
    # Panchanga
    "TithiPaksha",
    "YogaClass",
    "KaranaType",
    "VaraLordType",
    "PanchangaPolicy",
    "TITHI_NAMES",
    "YOGA_NAMES",
    "KARANA_NAMES",
    "VARA_LORDS",
    "VARA_NAMES",
    "RASHI_NAMES",
    "PanchangaElement",
    "PanchangaResult",
    "SankrantiResult",
    "TithiConditionProfile",
    "PanchangaProfile",
    "LunarMonthSystem", "LunarMonthPolicy", "CalendarBoundary", "LunarMonthLabel",
    "LunarLunation", "LunarMonthProvenance", "LunarMonthResult", "lunar_month_at",
    "PanchangaSunriseDefinition", "DailyPanchangaPolicy", "PanchangaMoment",
    "PanchangaSolarDate", "PanchangaLimbInterval", "PanchangaLimbDay",
    "DailyPanchangaProvenance", "DailyPanchangaResult", "daily_panchanga",
    "panchanga_at",
    "sankranti_at",
    "tithi_condition_profile",
    "panchanga_profile",
    "validate_panchanga_output",
    # Pancha Pakshi
    "PanchaPakshiActivity",
    "PanchaPakshiAdmissionStatus",
    "PanchaPakshiAstronomicalPaksha",
    "PanchaPakshiAstronomicalPakshaInference",
    "PanchaPakshiAstronomicalPakshaInferencePolicy",
    "PanchaPakshiBird",
    "PanchaPakshiCivilTimeSookshmaRoutingPolicy",
    "PanchaPakshiCivilTimeSookshmaSelection",
    "PanchaPakshiCapability",
    "PanchaPakshiConflictWitness",
    "PanchaPakshiCurrentCellSelectionStatus",
    "PanchaPakshiDataError",
    "PanchaPakshiDirectedRelationship",
    "PanchaPakshiError",
    "PanchaPakshiFixedClockCell",
    "PanchaPakshiFixedClockCurrentCellSelection",
    "PanchaPakshiFixedClockCurrentCellSelectionPolicy",
    "PanchaPakshiFixedClockMaterialization",
    "PanchaPakshiFixedClockMaterializationPolicy",
    "PanchaPakshiFirstEatBirdMapping",
    "PanchaPakshiHalf",
    "PanchaPakshiInitialVowelIdentity",
    "PanchaPakshiLocalSolarContext",
    "PanchaPakshiLocalSolarContextPolicy",
    "PanchaPakshiMaterializedCellRelation",
    "PanchaPakshiNakshatraBirdMapping",
    "PanchaPakshiNatalMoonIdentity",
    "PanchaPakshiNatalMoonIdentityPolicy",
    "PanchaPakshiOmission",
    "PanchaPakshiPaduBirdMapping",
    "PanchaPakshiPaksha",
    "PanchaPakshiProfileDescriptor",
    "PanchaPakshiProfileInfo",
    "PanchaPakshiProvenance",
    "PanchaPakshiRelation",
    "PanchaPakshiSchedule",
    "PanchaPakshiScheduleCell",
    "PanchaPakshiSolarProportionalCell",
    "PanchaPakshiSolarProportionalCurrentCellSelection",
    "PanchaPakshiSolarProportionalCurrentCellSelectionPolicy",
    "PanchaPakshiSolarProportionalMaterialization",
    "PanchaPakshiSolarProportionalMaterializationPolicy",
    "PanchaPakshiSolarBoundaryRelation",
    "PanchaPakshiSource",
    "PanchaPakshiSourceLocator",
    "PanchaPakshiScheduleSookshmaCompositionPolicy",
    "PanchaPakshiScheduleSookshmaSelection",
    "PanchaPakshiSookshmaInterval",
    "PanchaPakshiSookshmaSelection",
    "PanchaPakshiSookshmaSelectorPolicy",
    "PanchaPakshiSookshmaSelectorPolicyId",
    "PanchaPakshiSookshmaTimingPolicyId",
    "PanchaPakshiUromarisiConstitutionStatus",
    "PanchaPakshiWeekday",
    "available_pancha_pakshi_profiles",
    "pancha_pakshi_astronomical_paksha_at",
    "pancha_pakshi_civil_time_sookshma_selection_at",
    "pancha_pakshi_directed_relationship",
    "pancha_pakshi_fixed_clock_current_cell_at",
    "pancha_pakshi_fixed_clock_materialization_at",
    "pancha_pakshi_first_eat_bird_mapping",
    "pancha_pakshi_identity_from_initial_vowel",
    "pancha_pakshi_local_solar_context_at",
    "pancha_pakshi_nakshatra_bird_mapping",
    "pancha_pakshi_natal_moon_identity_at",
    "pancha_pakshi_padu_bird_mapping",
    "pancha_pakshi_profile_info",
    "pancha_pakshi_schedule",
    "pancha_pakshi_schedule_sookshma_temporal_selection",
    "pancha_pakshi_sookshma_temporal_selection",
    "pancha_pakshi_solar_proportional_current_cell_at",
    "pancha_pakshi_solar_proportional_materialization_at",
    "pancha_pakshi_uromarisi_constitution_status",
    # Vedic dignities
    "VedicDignityRank",
    "CompoundRelationship",
    "DignityTier",
    "EXALTATION_SIGN",
    "EXALTATION_DEGREE",
    "DEBILITATION_SIGN",
    "MULATRIKONA_SIGN",
    "MULATRIKONA_START",
    "MULATRIKONA_END",
    "OWN_SIGNS",
    "NATURAL_FRIENDS",
    "NATURAL_NEUTRALS",
    "NATURAL_ENEMIES",
    "VedicDignityResult",
    "PlanetaryRelationship",
    "VedicDignityPolicy",
    "DignityConditionProfile",
    "ChartDignityProfile",
    "vedic_dignity",
    "planetary_relationships",
    "dignity_condition_profile",
    "chart_dignity_profile",
    "validate_dignity_output",
    # Varga
    "VargaPoint",
    "calculate_varga",
    "navamsa",
    "saptamsa",
    "dashamansa",
    "dwadashamsa",
    "trimshamsa",
    "hora",
    "chaturthamsha",
    "shashthamsha",
    "ashtamsha",
    "shodashamsha",
    "vimshamsha",
    "chaturvimshamsha",
    "saptavimshamsha",
    "khavedamsha",
    "akshavedamsha",
    "shashtiamsha",
    # Vimshottari Dasha
    "VIMSHOTTARI_YEARS",
    "VIMSHOTTARI_SEQUENCE",
    "VIMSHOTTARI_TOTAL",
    "VIMSHOTTARI_YEAR_BASIS",
    "VIMSHOTTARI_LEVEL_NAMES",
    "DashaLordType",
    "VimshottariYearPolicy",
    "VimshottariAyanamsaPolicy",
    "VimshottariComputationPolicy",
    "DEFAULT_VIMSHOTTARI_POLICY",
    "DashaPeriod",
    "DashaActiveLine",
    "DashaConditionProfile",
    "DashaSequenceProfile",
    "DashaLordPair",
    "vimshottari",
    "current_dasha",
    "dasha_balance",
    "dasha_active_line",
    "dasha_condition_profile",
    "dasha_sequence_profile",
    "dasha_lord_pair",
    "validate_vimshottari_output",
    # Alternate dasha systems
    "AlternateDashaSystem",
    "ASHTOTTARI_YEARS",
    "ASHTOTTARI_SEQUENCE",
    "ASHTOTTARI_NAKSHATRA_LORD",
    "ASHTOTTARI_TOTAL",
    "YOGINI_YEARS",
    "YOGINI_SEQUENCE",
    "YOGINI_PLANETS",
    "YOGINI_TOTAL",
    "AlternateDashaPeriod",
    "AshtottariPolicy",
    "YoginiPolicy",
    "AlternatePeriodProfile",
    "AlternateDashaSequenceProfile",
    "ashtottari",
    "yogini_dasha",
    "alternate_period_profile",
    "alternate_sequence_profile",
    "validate_alternate_dasha_output",
    # Jaimini
    "KarakaRole",
    "KarakaPlanetType",
    "JaiminiPolicy",
    "KARAKA_NAMES_7",
    "KARAKA_NAMES_8",
    "KarakaAssignment",
    "JaiminiKarakaResult",
    "KarakaConditionProfile",
    "JaiminiChartProfile",
    "KarakaPair",
    "jaimini_karakas",
    "atmakaraka",
    "karaka_condition_profile",
    "jaimini_chart_profile",
    "karaka_pair",
    "validate_jaimini_output",
    # Ashtakavarga
    "RekhaTier",
    "AshtakavargaPolicy",
    "REKHA_TABLES",
    "BhinnashtakavargaResult",
    "AshtakavargaResult",
    "SignStrengthProfile",
    "AshtakavargaChartProfile",
    "bhinnashtakavarga",
    "ashtakavarga",
    "transit_strength",
    "sign_strength_profile",
    "ashtakavarga_chart_profile",
    "validate_ashtakavarga_output",
    # Gochara Phala
    "GOCHARA_PROFILE", "GOCHARA_PLANETS", "GocharaVedhaStatus",
    "GocharaPosition", "GocharaVedhaWitness", "GocharaPlanetResult",
    "GocharaResult", "gochara_from_positions",
    "DEFAULT_GOCHARA_POLICY", "GocharaSourceProfile", "GocharaVedhaMode",
    "GocharaCompleteness", "GocharaBavMode", "GocharaAdmissionStatus",
    "GocharaDoctrineOption", "GocharaPolicy", "gochara_doctrine_options",
    "GocharaBaselineClass", "GocharaBavAvailability", "GocharaVedhaRelationClass",
    "GocharaLocalCondition", "GocharaLocalProfile", "GocharaChartSummary",
    "GocharaNetworkNode", "GocharaVedhaNetwork", "GocharaSubsystemProfile",
    "gochara_local_profiles", "gochara_subsystem_profile",
    "GocharaNatalBavMode", "GocharaDatePolicy", "DEFAULT_GOCHARA_DATE_POLICY",
    "GocharaBirthLocation", "GocharaDatedPosition", "GocharaEpoch", "GocharaDateResult",
    "GocharaResourceError", "GocharaCoverageError", "gochara_at", "gochara_for_datetimes",
    # Shadbala
    "NAISARGIKA_BALA",
    "REQUIRED_RUPAS",
    "MEAN_DAILY_MOTION",
    "ShadbalaTier",
    "SthanaBala",
    "KalaBala",
    "PlanetShadbala",
    "ShadbalaResult",
    "ShadbalaPolicy",
    "ShadbalaContext",
    "ShadbalaContextError",
    "derive_shadbala_context",
    "SaptavargajaEntry",
    "saptavargaja_breakdown",
    "WarResolution",

    "ShadbalaConditionProfile",
    "ShadbalaChartProfile",
    "sthana_bala",
    "dig_bala",
    "kala_bala",
    "chesta_bala",
    "drig_bala",
    "shadbala",
    "hora_lord_at",
    "shadbala_condition_profile",
    "shadbala_chart_profile",
    "validate_shadbala_output",
    # Vedic returns
    "varshaphal",
    "varshaphal_chart",
    "TajikaPanchavargiStrength",
    "TajikaKalaBala",
    "TajikaChestaBala",
    "TajikaDrigBala",
    "TajikaShadbalaProfile",
    "VarshaphalActorJudgement",
    "VarshaphalSahamJudgement",
    "VarshaphalSahamPriority",
    "VarsheshaCandidate",
    "VarsheshaResult",
    "VarshaphalJudgementProfile",
    "VarshaphalYearJudgement",
    "VarshaphalTopicJudgement",
    "VarshaphalTopicWindow",
    "VarshaphalYearSummary",
    "TajikaAspectPolicy",
    "TajikaAspect",
    "TajikaYoga",
    "VarshaphalSahamDefinition",
    "VarshaphalSaham",
    "MunthaConditionProfile",
    "MuddaDashaPeriod",
    "MuddaDasha",
    "MuddaDashaActivation",
    "TasiraPeriod",
    "TasiraDasha",
    "MuddaPeriodJudgement",
    "MuddaPeriodResultProfile",
    "VarshaphalChart",
    "muntha",
    "mudda_dasha",
    "active_mudda_dasha",
    "tasira_periods",
    "active_tasira_period",
    "mudda_period_judgement",
    "tajika_panchavargi_strength",
    "tajika_shadbala_profile",
    "tajika_aspects",
    "tajika_yogas",
    "varshesha",
    "varshaphal_judgement_profile",
    "varshaphal_year_judgement",
    "varshaphal_topic_judgements",
    "varshaphal_topic_windows",
    "varshaphal_year_summary",
    "muntha_condition_profile",
    "varshaphal_sahams",
    "build_varshaphal_chart",
    # Varga strength and flags.
    "VIMSHOPAKA_GROUPS",
    "VARGA_VISHVA",
    "VimshopakaVargaEntry",
    "VimshopakaBala",
    "varga_sign_index",
    "vimshopaka_bala",
    "vimshopaka_all",
    "is_vargottama",
    "vargottama_planets",
    # ashtakavarga completion
    "KAKSHYA_LORDS",
    "RASIMANA",
    "GRAHAMANA",
    "KakshyaTransit",
    "ShodhyaPinda",
    "kakshya_transit",
    "shodhya_pinda",
    # shadbala completion
    "BhavaBala",
    "BhavaBalaResult",
    "bhava_bala",
    "bhava_dig_bala",
    "bhava_drishti_bala",
    # yogas completion
    "YogaPolicy",
    "YogaCondition",
    "YogaResult",
    "YogaChartResult",
    "benefic_malefic_classification",
    "pancha_mahapurusha_yogas",
    "chandra_yogas",
    "surya_yogas",
    "nabhasa_yogas",
    "raja_yogas",
    "dhana_yogas",
    "evaluate_yogas",
    # avasthas completion
    "AvasthaPolicy",
    "SayanadiAvastha",
    "SayanadiPolicy",
    "SayanadiName",
    "SayanadiGhati",
    "SayanadiContext",
    "SayanadiTrace",
    "SayanadiEffectProvenance",
    "sayanadi_avastha",
    "sayanadi_ghati_from_elapsed",
    "SayanadiBirthPolicy",
    "SayanadiSunriseBracket",
    "AvasthaBirthResult",
    "SayanadiResourceError",
    "SayanadiCoverageError",
    "avasthas_for_datetime",
    "BaladiAvastha",
    "JagradadiAvastha",
    "DeeptadiAvastha",
    "LajjitadiState",
    "LajjitadiAvasthas",
    "PlanetAvasthas",
    "AvasthaChartResult",
    "baladi_avastha",
    "jagradadi_avastha",
    "deeptadi_avastha",
    "lajjitadi_avasthas",
    "evaluate_avasthas",
    # jaimini_extended completion
    "JaiminiExtendedPolicy",
    "rasi_aspects",
    "rasi_drishti_of",
    "ArudhaPada",
    "ArudhaResult",
    "arudha_padas",
    "ArgalaHouse",
    "ArgalaResult",
    "argala",
    "Karakamsa",
    "karakamsa",
    "CharaDashaPeriod",
    "CharaDashaResult", "CharaDashaComputation",
    "chara_dasha",
    # muhurta completion
    "MuhurtaPolicy",
    "MuhurtaClassification",
    "MuhurtaScore",
    "classify_muhurta",
    "score_muhurta",
    "TARA_NAMES",
    "TaraBala",
    "tara_bala",
    "ChandraBala",
    "chandra_bala",
    "PersonalMuhurtaScore",
    "personal_muhurta_score",
    'PanchangaShuddhiPolicy',
    'ShuddhiBoundary',
    'ShuddhiInterval',
    'ShuddhiFinding',
    'ShuddhiInputs',
    'ShuddhiValues',
    'PanchangaShuddhiAssessment',
    'ShuddhiCatalogueEntry',
    'ShuddhiCatalogue',
    'PanchakaRahita',
    'ShuddhiCell',
    'PanchangaShuddhiDay',
    'panchanga_shuddhi_catalogue',
    'panchanga_shuddhi_from_longitudes',
    'panchaka_rahita',
    'panchanga_shuddhi_for_date',
    "SpecialMuhurtaPolicy", "SpecialMuhurtaBoundary", "SpecialMuhurtaWindow", "SpecialMuhurtaResult", "SpecialMuhurtaSolarResult", "MuhurtaYogaMatch", "MuhurtaYogaSnapshot", "SpecialMuhurtaDay", "special_muhurta_from_solar_times", "muhurta_yogas_from_longitudes", "special_muhurta_for_date",
    "NamedMuhurtaPolicy", "NamedMuhurtaAnchor", "NamedMuhurtaInterval", "NamedMuhurtaResult", "NamedMuhurtaDay", "named_muhurta_from_solar_times", "named_muhurta_for_date",
    "MuhurtaSearchPolicy", "MuhurtaMomentScore", "MuhurtaSearchWindow", "MuhurtaSearchResult", "MuhurtaResourceError", "MuhurtaCoverageError", "muhurta_score_for_chart", "find_muhurta_windows",
    # upagrahas completion
    "UpagrahaPolicy",
    "SunBasedUpagrahas",
    "KalavelaUpagraha",
    "KalavelaResult",
    "sun_based_upagrahas",
    "kalavela_upagrahas",
    # sade_sati completion
    "SADE_SATI_PHASES",
    "SadeSatiStatus",
    "SadeSatiWindow",
    "SadeSatiResult",
    "SadeSatiBudgetError",
    "DEFAULT_SADE_SATI_EVALUATIONS",
    "MAX_SADE_SATI_EVALUATIONS",

    "sade_sati_status",
    "sade_sati_windows",
]

__all__ = list(_essentials_all) + _VEDIC_OWN
