"""
tests/integration/test_aspects_external_reference.py

Validate Moira's aspect engine against an offline fixture derived from the
externally-validated planet_at() pipeline.

Validation layers
-----------------
Layer A — position substrate:
    The ecliptic longitudes in the fixture were produced by Moira's own
    planet_at() pipeline, which is externally validated against JPL Horizons
    (test_horizons_planet_apparent.py, 120 cases, worst angular error 0.576").
    Storing those positions anchors the aspect geometry to a validated
    astronomical substrate.

Layer C — angular_distance arithmetic:
    For every stored body pair the fixture records the expected angular
    separation and expected aspect name.  The test recomputes those
    separations from scratch via find_aspects() and verifies:
      - every expected pair is found (correct bodies, correct aspect name)
      - the recomputed orb matches the stored orb within PASS_THRESHOLD_DEG
      - no spurious aspects appear outside the tight-orb window

Fixture
-------
    tests/fixtures/aspects_reference.json
    Generated by: scripts/build_aspects_fixture.py

Markers
-------
    integration, requires_ephemeris
    No live network call is made — the fixture must be pre-generated with
    build_aspects_fixture.py.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from moira.aspects import find_aspects
from moira.constants import Aspect

_FIXTURE = Path(__file__).resolve().parents[1] / "fixtures" / "aspects_reference.json"

PASS_THRESHOLD_DEG = 1e-6

_MAJOR_ANGLE_SET: frozenset[float] = frozenset(adef.angle for adef in Aspect.MAJOR)


def _load_epoch_params() -> list[pytest.param]:
    if not _FIXTURE.exists():
        return []
    data = json.loads(_FIXTURE.read_text(encoding="utf-8"))
    params = []
    for epoch in data.get("epochs", []):
        params.append(
            pytest.param(
                epoch["label"],
                epoch["jd_ut"],
                epoch["cases"],
                id=epoch["label"],
            )
        )
    return params


_EPOCH_PARAMS = _load_epoch_params()


@pytest.mark.integration
@pytest.mark.requires_ephemeris
@pytest.mark.skipif(
    not _FIXTURE.exists(),
    reason="aspects_reference.json not found — run scripts/build_aspects_fixture.py first",
)
@pytest.mark.parametrize(("label", "jd_ut", "expected_cases"), _EPOCH_PARAMS)
def test_aspects_match_fixture_positions(
    label: str,
    jd_ut: float,
    expected_cases: list[dict],
) -> None:
    """
    Layer A + C: feed stored longitudes into find_aspects() and verify that
    every expected aspect is detected with the correct orb.
    """
    if not expected_cases:
        pytest.skip(f"{label}: no tight-orb aspects in fixture")

    positions: dict[str, float] = {}
    for case in expected_cases:
        positions[case["body1"]] = case["lon1_deg"]
        positions[case["body2"]] = case["lon2_deg"]

    orbs: dict[float, float] = {angle: 1.0 for angle in _MAJOR_ANGLE_SET}
    found = find_aspects(positions, orbs=orbs, include_minor=False)

    found_index: dict[tuple[str, str, str], float] = {
        (a.body1, a.body2, a.aspect): a.orb for a in found
    }

    for case in expected_cases:
        b1, b2 = case["body1"], case["body2"]
        aspect_name = case["aspect"]
        expected_orb = case["orb_deg"]

        key = (b1, b2, aspect_name)
        assert key in found_index, (
            f"{label}: expected {b1} {aspect_name} {b2} not found in find_aspects() output.  "
            f"stored orb={expected_orb:.6f}°  lon1={case['lon1_deg']:.6f}°  "
            f"lon2={case['lon2_deg']:.6f}°"
        )

        actual_orb = found_index[key]
        delta = abs(actual_orb - expected_orb)
        assert delta <= PASS_THRESHOLD_DEG, (
            f"{label}: {b1} {aspect_name} {b2} orb mismatch — "
            f"expected {expected_orb:.8f}°, got {actual_orb:.8f}°, "
            f"delta={delta:.2e}°"
        )


@pytest.mark.integration
@pytest.mark.requires_ephemeris
@pytest.mark.skipif(
    not _FIXTURE.exists(),
    reason="aspects_reference.json not found — run scripts/build_aspects_fixture.py first",
)
@pytest.mark.parametrize(("label", "jd_ut", "expected_cases"), _EPOCH_PARAMS)
def test_angular_distance_correctness(
    label: str,
    jd_ut: float,
    expected_cases: list[dict],
) -> None:
    """
    Layer C: directly verify that angular_distance(lon1, lon2) reproduces the
    stored separation for every body pair in the fixture, independently of
    the aspect engine.
    """
    from moira.coordinates import angular_distance

    for case in expected_cases:
        lon1 = case["lon1_deg"]
        lon2 = case["lon2_deg"]
        expected_sep = case["separation_deg"]

        actual_sep = angular_distance(lon1, lon2)
        delta = abs(actual_sep - expected_sep)

        assert delta <= PASS_THRESHOLD_DEG, (
            f"{label}: angular_distance({lon1:.6f}°, {lon2:.6f}°) — "
            f"expected {expected_sep:.8f}°, got {actual_sep:.8f}°, "
            f"delta={delta:.2e}°"
        )


@pytest.mark.integration
@pytest.mark.requires_ephemeris
@pytest.mark.skipif(
    not _FIXTURE.exists(),
    reason="aspects_reference.json not found — run scripts/build_aspects_fixture.py first",
)
def test_fixture_covers_all_four_epochs() -> None:
    """Guard: fixture must contain all four expected epochs."""
    data = json.loads(_FIXTURE.read_text(encoding="utf-8"))
    found_labels = {e["label"] for e in data.get("epochs", [])}
    expected_labels = {"J1900", "J1950", "J2000", "J2024"}
    assert expected_labels <= found_labels, (
        f"Missing epochs in fixture: {expected_labels - found_labels}"
    )


@pytest.mark.integration
@pytest.mark.requires_ephemeris
@pytest.mark.skipif(
    not _FIXTURE.exists(),
    reason="aspects_reference.json not found — run scripts/build_aspects_fixture.py first",
)
def test_fixture_tight_orb_window_is_one_degree() -> None:
    """Guard: fixture must declare a 1.0-degree tight-orb window."""
    data = json.loads(_FIXTURE.read_text(encoding="utf-8"))
    assert data.get("_tight_orb_deg") == 1.0, (
        f"Expected tight-orb window of 1.0°, got {data.get('_tight_orb_deg')}"
    )
