"""
Harmograms Research Engine.

This package exposes a research-facing harmograms subsystem with explicit
policies, spectral vessels, projection machinery, time-domain traces, and
comparison helpers. Astronomical generation is intentionally out of scope.
"""

from __future__ import annotations

from .compute import (
    _compute_components,
    _compute_intensity_components,
    harmonic_vector,
    harmogram_trace,
    intensity_function_spectrum,
    parts_from_zero_aries,
    point_set_harmonic_vector,
    project_harmogram_strength,
    zero_aries_parts_harmonic_vector,
)
from .helpers import (
    _intensity_at_angle_deg,
    _normalize_angle_deg,
    _normalize_positions,
    _signed_smallest_angle_deg,
    _validate_component_domain,
)
from .models import (
    GaussianWidthParameterMode,
    HarmogramChartDomain,
    HarmogramDominantTerm,
    HarmogramIntensityFamily,
    HarmogramIntensityPolicy,
    HarmogramOrbMode,
    HarmogramOrbScalingMode,
    HarmogramOutputMode,
    HarmogramPolicy,
    HarmogramProjection,
    HarmogramProjectionRealizationMode,
    HarmogramProjectionTerm,
    HarmogramSamplingMode,
    HarmogramSamplingPolicy,
    HarmogramSymmetryMode,
    HarmogramTrace,
    HarmogramTraceFamily,
    HarmogramTraceSample,
    HarmogramTraceSeries,
    HarmogramTraceSeriesComparison,
    HarmogramTraceSeriesComparisonSample,
    HarmonicDomain,
    HarmonicVectorComponent,
    HarmonicVectorNormalizationMode,
    IntensityFunctionSpectrum,
    IntensityNormalizationMode,
    IntensitySpectrumComparison,
    IntensitySpectrumComparisonTerm,
    IntensitySpectrumComponent,
    IntensitySpectrumRealizationMode,
    PointSetHarmonicVector,
    PointSetHarmonicVectorPolicy,
    SelfPairMode,
    ZeroAriesPairConstructionMode,
    ZeroAriesPart,
    ZeroAriesPartsHarmonicVector,
    ZeroAriesPartsPolicy,
    ZeroAriesPartsSet,
)
from .research import compare_intensity_spectra, compare_trace_series, dominant_harmonic_contributors

__all__ = [
    "HarmonicVectorNormalizationMode",
    "ZeroAriesPairConstructionMode",
    "SelfPairMode",
    "HarmonicDomain",
    "PointSetHarmonicVectorPolicy",
    "ZeroAriesPartsPolicy",
    "HarmonicVectorComponent",
    "PointSetHarmonicVector",
    "ZeroAriesPart",
    "ZeroAriesPartsSet",
    "ZeroAriesPartsHarmonicVector",
    "HarmogramIntensityFamily",
    "HarmogramOrbMode",
    "GaussianWidthParameterMode",
    "HarmogramOrbScalingMode",
    "HarmogramSymmetryMode",
    "IntensityNormalizationMode",
    "IntensitySpectrumRealizationMode",
    "HarmogramProjectionRealizationMode",
    "HarmogramSamplingMode",
    "HarmogramOutputMode",
    "HarmogramChartDomain",
    "HarmogramTraceFamily",
    "HarmogramIntensityPolicy",
    "HarmogramSamplingPolicy",
    "HarmogramPolicy",
    "IntensitySpectrumComponent",
    "IntensityFunctionSpectrum",
    "HarmogramProjectionTerm",
    "HarmogramProjection",
    "HarmogramDominantTerm",
    "IntensitySpectrumComparisonTerm",
    "IntensitySpectrumComparison",
    "HarmogramTraceSeriesComparisonSample",
    "HarmogramTraceSeriesComparison",
    "HarmogramTraceSample",
    "HarmogramTraceSeries",
    "HarmogramTrace",
    "point_set_harmonic_vector",
    "parts_from_zero_aries",
    "zero_aries_parts_harmonic_vector",
    "intensity_function_spectrum",
    "project_harmogram_strength",
    "harmogram_trace",
    "dominant_harmonic_contributors",
    "compare_intensity_spectra",
    "compare_trace_series",
    "harmonic_vector",
]
