#!/usr/bin/env python
"""
Build an offline Swiss swetest fixture for progressions and solar arc.

The fixture stores Swiss reference positions at the progressed date for
secondary progressions, and Swiss-derived solar-arc values for directed
longitudes. Tests then run fully offline against the generated fixture.

Usage
-----
    py -3.14 scripts/build_progressions_swetest_fixture.py
"""

from __future__ import annotations

from datetime import datetime, timezone
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from moira.julian import datetime_from_jd, jd_from_datetime
from tests.tools.swetest import fetch_swetest_snapshot


TROPICAL_YEAR = 365.24219
FIXTURE_PATH = ROOT / "tests" / "fixtures" / "progressions_swetest_reference.json"
BODIES = (
    "Sun",
    "Moon",
    "Mercury",
    "Venus",
    "Mars",
    "Jupiter",
    "Saturn",
    "Uranus",
    "Neptune",
    "Pluto",
)

CASES = (
    {
        "id": "secondary_1990_2020",
        "natal_dt_utc": datetime(1990, 1, 1, 6, 0, tzinfo=timezone.utc),
        "target_dt_utc": datetime(2020, 1, 1, 6, 0, tzinfo=timezone.utc),
    },
    {
        "id": "secondary_1987_2024_eclipse",
        "natal_dt_utc": datetime(1987, 9, 23, 4, 0, tzinfo=timezone.utc),
        "target_dt_utc": datetime(2024, 4, 8, 18, 0, tzinfo=timezone.utc),
    },
    {
        "id": "secondary_1992_2020_summer",
        "natal_dt_utc": datetime(1992, 7, 15, 18, 0, tzinfo=timezone.utc),
        "target_dt_utc": datetime(2020, 6, 1, 0, 0, tzinfo=timezone.utc),
    },
)


def _iso(dt: datetime) -> str:
    return dt.astimezone(timezone.utc).isoformat()


def _progressed_dt(natal_dt: datetime, target_dt: datetime) -> datetime:
    natal_jd = jd_from_datetime(natal_dt)
    target_jd = jd_from_datetime(target_dt)
    age_years = (target_jd - natal_jd) / TROPICAL_YEAR
    return datetime_from_jd(natal_jd + age_years).astimezone(timezone.utc)


def _rounded_positions(snapshot) -> dict[str, float]:
    return {
        body: round(snapshot.positions[body].longitude_deg, 10)
        for body in BODIES
    }


def build() -> None:
    secondary_cases: list[dict] = []
    solar_arc_cases: list[dict] = []

    for case in CASES:
        natal_dt = case["natal_dt_utc"]
        target_dt = case["target_dt_utc"]
        progressed_dt = _progressed_dt(natal_dt, target_dt)

        natal_snapshot = fetch_swetest_snapshot(natal_dt)
        progressed_snapshot = fetch_swetest_snapshot(progressed_dt)

        arc_deg = (
            progressed_snapshot.positions["Sun"].longitude_deg
            - natal_snapshot.positions["Sun"].longitude_deg
        ) % 360.0

        secondary_cases.append(
            {
                "id": case["id"],
                "natal_dt_utc": _iso(natal_dt),
                "target_dt_utc": _iso(target_dt),
                "progressed_dt_utc": _iso(progressed_dt),
                "swetest_url": progressed_snapshot.source_url,
                "jd_ut": progressed_snapshot.jd_ut,
                "jd_tt": progressed_snapshot.jd_tt,
                "positions_deg": _rounded_positions(progressed_snapshot),
            }
        )

        solar_arc_cases.append(
            {
                "id": case["id"].replace("secondary_", "solar_arc_"),
                "natal_dt_utc": _iso(natal_dt),
                "target_dt_utc": _iso(target_dt),
                "progressed_dt_utc": _iso(progressed_dt),
                "natal_swetest_url": natal_snapshot.source_url,
                "progressed_swetest_url": progressed_snapshot.source_url,
                "arc_deg": round(arc_deg, 10),
                "positions_deg": {
                    body: round((natal_snapshot.positions[body].longitude_deg + arc_deg) % 360.0, 10)
                    for body in BODIES
                },
            }
        )

    fixture = {
        "_comment": (
            "Offline Swiss swetest reference for secondary progressions and solar arc. "
            "Secondary cases store Swiss longitudes at the progressed date derived by "
            "the canonical one-day-for-one-year key. Solar-arc cases store the Swiss "
            "progressed-Sun minus natal-Sun arc applied to Swiss natal longitudes. "
            "Generated by scripts/build_progressions_swetest_fixture.py."
        ),
        "_source": "Astro.com Swiss swetest CGI",
        "_bodies": list(BODIES),
        "_threshold_arcsec": 1.0,
        "secondary_cases": secondary_cases,
        "solar_arc_cases": solar_arc_cases,
    }

    FIXTURE_PATH.write_text(
        json.dumps(fixture, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    print(f"Wrote {FIXTURE_PATH}")


if __name__ == "__main__":
    build()
