#!/usr/bin/env python
"""
scripts/build_aspects_fixture.py

Generate the offline aspect-validation fixture for Moira.

Strategy
--------
Aspect detection is pure geometry on top of ecliptic longitudes.  Rather than
comparing Moira against an external oracle that uses different orb conventions,
we validate in two layers:

  Layer A — positions:
    The ecliptic longitudes stored in the fixture are produced by Moira's own
    planet_at() pipeline, which is already externally validated against JPL
    Horizons (test_horizons_planet_apparent.py, 120 cases, worst error 0.576").
    Storing those positions in the fixture anchors the aspect geometry to a
    validated astronomical substrate.

  Layer C — angular_distance arithmetic:
    For every stored body pair we record the expected angular separation and
    the expected aspect name (if within the tight-orb window).  The integration
    test recomputes those separations from scratch and compares, verifying
    that angular_distance() is correct for the full range of longitude pairs
    that actually arise in practice.

Fixture design
--------------
  - 4 chart epochs: J1900, J1950, J2000, J2024
  - 10 major bodies: Sun through Pluto (Body.ALL_PLANETS)
  - Only aspects within a TIGHT_ORB_DEG window (1.0°) around exact are stored.
    This keeps the fixture stable: a case that is 0.3° from exact cannot drift
    in or out of the window due to floating-point differences in future builds.
  - Tier 0 (major aspects only): Conjunction, Sextile, Square, Trine, Opposition.
    Minor aspects are covered by the unit test suite; the oracle layer focuses
    on the geometrically unambiguous major set.

Usage
-----
    py -3.14 scripts/build_aspects_fixture.py

Output
------
    tests/fixtures/aspects_reference.json
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_ROOT))

from moira.constants import Body, Aspect
from moira.coordinates import angular_distance
from moira.julian import julian_day
from moira.planets import all_planets_at
from moira.spk_reader import get_reader

_FIXTURE_PATH = _ROOT / "tests" / "fixtures" / "aspects_reference.json"

TIGHT_ORB_DEG = 1.0

MAJOR_ASPECTS: list[tuple[str, float]] = [
    (adef.name, adef.angle) for adef in Aspect.MAJOR
]

EPOCHS: list[tuple[str, float]] = [
    ("J1900", julian_day(1900, 1, 1, 12.0)),
    ("J1950", julian_day(1950, 1, 1, 12.0)),
    ("J2000", julian_day(2000, 1, 1, 12.0)),
    ("J2024", julian_day(2024, 1, 1, 12.0)),
]

BODIES: list[str] = list(Body.ALL_PLANETS)


def _compute_cases(jd_ut: float, label: str, reader) -> list[dict]:
    planet_map = all_planets_at(jd_ut, BODIES, reader)
    positions: dict[str, float] = {
        p.name: p.longitude for p in planet_map.values()
    }

    body_list = list(positions.keys())
    cases: list[dict] = []

    for i in range(len(body_list)):
        for j in range(i + 1, len(body_list)):
            b1, b2 = body_list[i], body_list[j]
            lon1, lon2 = positions[b1], positions[b2]
            sep = angular_distance(lon1, lon2)

            for aspect_name, exact_angle in MAJOR_ASPECTS:
                orb = abs(sep - exact_angle)
                if orb <= TIGHT_ORB_DEG:
                    cases.append({
                        "body1": b1,
                        "body2": b2,
                        "lon1_deg": round(lon1, 8),
                        "lon2_deg": round(lon2, 8),
                        "separation_deg": round(sep, 8),
                        "aspect": aspect_name,
                        "exact_angle_deg": exact_angle,
                        "orb_deg": round(orb, 8),
                    })

    return cases


def build() -> None:
    reader = get_reader()

    fixture: dict = {
        "_comment": (
            "Offline aspect-validation fixture for Moira.  "
            "Positions are from Moira's planet_at() pipeline, which is "
            "externally validated against JPL Horizons "
            "(test_horizons_planet_apparent.py, 120 cases, worst error 0.576\").  "
            "Only major aspects (tier 0) within a 1.0-degree tight-orb window are stored.  "
            "Generated by scripts/build_aspects_fixture.py."
        ),
        "_tight_orb_deg": TIGHT_ORB_DEG,
        "_aspect_tier": 0,
        "_bodies": BODIES,
        "_epochs": [label for label, _ in EPOCHS],
        "epochs": [],
    }

    total_cases = 0
    for label, jd_ut in EPOCHS:
        print(f"  Computing {label} (JD {jd_ut:.1f}) ...", end=" ", flush=True)
        cases = _compute_cases(jd_ut, label, reader)
        fixture["epochs"].append({
            "label": label,
            "jd_ut": jd_ut,
            "cases": cases,
        })
        print(f"{len(cases)} aspects within tight-orb window")
        total_cases += len(cases)

    _FIXTURE_PATH.parent.mkdir(parents=True, exist_ok=True)
    _FIXTURE_PATH.write_text(
        json.dumps(fixture, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )

    print(f"\nWrote {_FIXTURE_PATH}")
    print(f"Total cases: {total_cases} across {len(EPOCHS)} epochs")


if __name__ == "__main__":
    build()
