#!/usr/bin/env python
"""
Build an offline Swiss swetest fixture for sovereign fixed-star auditing.

This script queries Astro.com swetest for a narrow anchor set and writes a
fixture consumed by integration tests. The runtime engine remains sovereign;
Swiss is used here only as an external audit oracle.
"""

from __future__ import annotations

from datetime import datetime, timezone
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from tests.tools.swetest import fetch_swetest_fixed_star_snapshot


FIXTURE_PATH = ROOT / "tests" / "fixtures" / "stars_swetest_reference.json"
STAR_NAMES = ("Sirius", "Algol", "Spica", "Aldebaran")
DATE_CASES = (
    ("j1000_ut0", datetime(1000, 1, 1, 0, 0, tzinfo=timezone.utc)),
    ("j1500_ut0", datetime(1500, 1, 1, 0, 0, tzinfo=timezone.utc)),
    ("j1900_ut0", datetime(1900, 1, 1, 0, 0, tzinfo=timezone.utc)),
    ("j2000_ut0", datetime(2000, 1, 1, 0, 0, tzinfo=timezone.utc)),
    ("j2100_ut0", datetime(2100, 1, 1, 0, 0, tzinfo=timezone.utc)),
    ("j2500_ut0", datetime(2500, 1, 1, 0, 0, tzinfo=timezone.utc)),
    ("j3000_ut0", datetime(3000, 1, 1, 0, 0, tzinfo=timezone.utc)),
)


def _iso(dt: datetime) -> str:
    return dt.astimezone(timezone.utc).isoformat()


def build() -> None:
    cases: list[dict[str, object]] = []

    for case_id, dt_utc in DATE_CASES:
        stars: dict[str, dict[str, object]] = {}
        for star_name in STAR_NAMES:
            snapshot = fetch_swetest_fixed_star_snapshot(dt_utc, star_name)
            stars[star_name] = {
                "designation": snapshot.position.designation,
                "jd_ut": snapshot.jd_ut,
                "jd_tt": snapshot.jd_tt,
                "longitude_deg": round(snapshot.position.longitude_deg, 10),
                "latitude_deg": round(snapshot.position.latitude_deg, 10),
                "distance_au": round(snapshot.position.distance_au, 10),
                "url": snapshot.source_url,
            }

        cases.append(
            {
                "id": case_id,
                "datetime_utc": _iso(dt_utc),
                "stars": stars,
            }
        )

    payload = {
        "_comment": (
            "Offline Swiss swetest reference for sovereign fixed-star auditing. "
            "Each case stores Swiss tropical ecliptic longitude/latitude for the "
            "named fixed star at the given UTC epoch, plus both JD_UT and JD_TT "
            "reported by Swiss. Generated by scripts/build_stars_swetest_fixture.py."
        ),
        "_source": "Astro.com Swiss swetest CGI",
        "_stars": list(STAR_NAMES),
        "_case_count": len(cases),
        "cases": cases,
    }

    FIXTURE_PATH.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    print(f"Wrote {FIXTURE_PATH}")


if __name__ == "__main__":
    build()
