#!/usr/bin/env python
"""
Build an offline JPL Horizons fixture for rise/set/transit validation.

This script fetches apparent topocentric event times from Horizons-derived sky
samples and writes them to ``tests/fixtures/horizons_rise_set_reference.json``.
The resulting fixture is used by offline integration tests; no network is used
at test time.

Usage
-----
    py -3.14 scripts/build_rise_set_horizons_fixture.py
"""

from __future__ import annotations

import json
import sys
import time
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_ROOT))

from moira.julian import datetime_from_jd
from tests.tools.horizons import observer_event_times

_FIXTURE_PATH = _ROOT / "tests" / "fixtures" / "horizons_rise_set_reference.json"
_REQUEST_SLEEP_SECONDS = 1.5


_CASES: list[dict[str, object]] = [
    {
        "id": "sun-new-york-equinox",
        "body": "Sun",
        "command": "10",
        "label": "New York City, USA",
        "jd_start": 2460389.5,
        "latitude_deg": 40.7128,
        "longitude_deg": -74.0060,
        "altitude_deg": -0.8333,
        "threshold_seconds": 2.0,
        "notes": "Mid-latitude Sun case with all four events present.",
    },
    {
        "id": "moon-new-york-autumn",
        "body": "Moon",
        "command": "301",
        "label": "New York City, USA",
        "jd_start": 2460583.5,
        "latitude_deg": 40.7128,
        "longitude_deg": -74.0060,
        "altitude_deg": -0.8333,
        "threshold_seconds": 2.0,
        "notes": "Moon case at a populated mid-latitude site.",
    },
    {
        "id": "venus-sydney-summer",
        "body": "Venus",
        "command": "299",
        "label": "Sydney, Australia",
        "jd_start": 2460324.5,
        "latitude_deg": -33.8688,
        "longitude_deg": 151.2093,
        "altitude_deg": -0.5667,
        "threshold_seconds": 2.0,
        "notes": "Bright-planet case in the southern hemisphere with east longitude.",
    },
    {
        "id": "sun-tromso-midsummer",
        "body": "Sun",
        "command": "10",
        "label": "Tromso, Norway",
        "jd_start": 2460482.5,
        "latitude_deg": 69.6492,
        "longitude_deg": 18.9553,
        "altitude_deg": -0.8333,
        "threshold_seconds": 2.0,
        "notes": "High-latitude no-rise/no-set case; transit and anti-transit still occur.",
    },
]


def _serialize_case(case: dict[str, object], oracle: dict[str, float | None]) -> dict[str, object]:
    jd_start = float(case["jd_start"])
    return {
        "id": case["id"],
        "body": case["body"],
        "command": case["command"],
        "location": {
            "label": case["label"],
            "latitude_deg": case["latitude_deg"],
            "longitude_deg": case["longitude_deg"],
            "elevation_km": 0.0,
        },
        "window": {
            "jd_start": jd_start,
            "start_utc": datetime_from_jd(jd_start).strftime("%Y-%m-%dT%H:%M:%SZ"),
            "duration_hours": 24.0,
            "semantics": "next 24h from jd_start",
        },
        "altitude_deg": case["altitude_deg"],
        "threshold_seconds": case["threshold_seconds"],
        "source": {
            "oracle": "JPL Horizons",
            "method": (
                "OBSERVER topocentric samples with QUANTITIES=4,42; "
                "rise/set derived from altitude-threshold crossings, "
                "transit/anti-transit from local apparent hour-angle crossings."
            ),
            "step_size": "1 m",
            "time_type": "UT",
        },
        "expected_events": oracle,
        "notes": case["notes"],
    }


def main() -> None:
    print(f"Fetching {len(_CASES)} rise/set oracle case(s) from JPL Horizons...")
    results: list[dict[str, object]] = []

    for index, case in enumerate(_CASES, start=1):
        print(
            f"[{index}/{len(_CASES)}] {case['body']} @ {case['label']} ...",
            end=" ",
            flush=True,
        )
        oracle = observer_event_times(
            str(case["command"]),
            float(case["jd_start"]),
            float(case["latitude_deg"]),
            float(case["longitude_deg"]),
            altitude_deg=float(case["altitude_deg"]),
            step_size="1 m",
        )
        results.append(_serialize_case(case, oracle))
        printable = ", ".join(
            f"{name}={value:.9f}" if value is not None else f"{name}=None"
            for name, value in oracle.items()
        )
        print(printable)
        if index < len(_CASES):
            time.sleep(_REQUEST_SLEEP_SECONDS)

    fixture = {
        "_comment": (
            "Offline Horizons rise/set/transit reference cases for Sun, Moon, and Venus, "
            "including a high-latitude no-rise/no-set Sun case. Generated by "
            "scripts/build_rise_set_horizons_fixture.py."
        ),
        "_source": (
            "Primary oracle: JPL Horizons observer tables sampled at 1-minute cadence. "
            "No network is required at test time."
        ),
        "_generated": "see git log",
        "_default_threshold_seconds": 2.0,
        "cases": results,
    }

    _FIXTURE_PATH.write_text(json.dumps(fixture, indent=2), encoding="utf-8")
    print(f"\nWrote {len(results)} case(s) to {_FIXTURE_PATH}")


if __name__ == "__main__":
    main()
