"""Observational visibility doctrine.

The default policy preserves Moira's established arcus-visionis limiting-
magnitude behavior and Yallop lunar-crescent path.  A separate opt-in physical
point-source path keeps three products visible:

* auditable direct target extinction, using either a declared measured
  coefficient with Kasten--Young (1989) air mass or Schaefer's (1993)
  Rayleigh/aerosol/ozone component estimate;
* directional cloudless-sky twilight brightness from Schaefer (1993), with
  Krisciunas & Schaefer (1991) dark-sky and optional moonlight contributions;
* the scotopic naked-eye point-source threshold from Crumey (2014), evaluated
  only inside the paper's published background-luminance interval.

The physical path is explicitly policy-selected.  It is not a daylight model,
does not extrapolate Crumey's fit, does not treat the Sun or Moon as unresolved
point sources, and does not replace the legacy heliacal event-search doctrine.
Crumey's overall field factor includes the observing medium by default, so the
separately reported target extinction is not counted twice.
Schaefer's component path also keeps its scotopic target coefficient separate
from the visual-band coefficient consumed by the sky-brightness equations.
"""

from __future__ import annotations

from moira.heliacal import (
    AtmosphericExtinctionAssessment,
    ExtinctionCoefficient,
    GeneralVisibilityEvent,
    HeliacalEventKind,
    HeliacalPolicy,
    LightPollutionClass,
    LightPollutionDerivationMode,
    LunarCrescentDetails,
    LunarCrescentVisibilityClass,
    MoonlightPolicy,
    ObserverAid,
    ObserverVisibilityEnvironment,
    PlanetHeliacalEvent,
    PointSourceVisibilityThreshold,
    PhysicalAtmosphereInput,
    PhysicalAtmosphereReceipt,
    PhysicalBackgroundComponentKind,
    PhysicalBackgroundReceipt,
    PhysicalBackgroundScope,
    PhysicalBortleBackground,
    PhysicalDirectionalBackground,
    PhysicalEphemerisReceipt,
    PhysicalEventSensitivityReceipt,
    PhysicalEventSolverReceipt,
    PhysicalEventTimeSemantics,
    PhysicalHorizonProfile,
    PhysicalHorizonReceipt,
    PhysicalHorizonSample,
    PhysicalModeledBackgroundComponent,
    PhysicalObservationWindowReceipt,
    PhysicalObserverProtocolReceipt,
    PhysicalSqmBackground,
    PhysicalTargetReceipt,
    PhysicalThresholdReceipt,
    PhysicalValidityDomainReceipt,
    PhysicalVisibilityAssessment,
    PhysicalVisibilityBoundarySource,
    PhysicalVisibilityCrossingDirection,
    PhysicalVisibilityErrorBudgetReceipt,
    PhysicalVisibilityEventResult,
    PhysicalVisibilityEvidenceState,
    PhysicalVisibilityPhase,
    PhysicalVisibilityPolicy,
    PhysicalVisibilitySearchPolicy,
    PhysicalVisibilityStatus,
    TwilightSkyBrightnessAssessment,
    VisibilityComponentReceipt,
    VisibilityDataPackConfig,
    VisibilityDataPackReceipt,
    VisibilityAssessment,
    VisibilityCriterionFamily,
    VisibilityExtinctionModel,
    VisibilityModel,
    VisibilityPolicy,
    VisibilitySearchPolicy,
    VisibilityTargetKind,
    VisibilityTwilightModel,
    atmospheric_extinction,
    directional_twilight_sky_brightness,
    is_visible_tonight,
    planet_acronychal_rising,
    planet_acronychal_setting,
    planet_heliacal_rising,
    planet_heliacal_setting,
    point_source_visibility_threshold,
    physical_visibility_assessment,
    physical_visibility_event,
    relative_optical_airmass,
    visibility_assessment,
    visibility_event,
    visibility_tonight,
    visual_limiting_magnitude,
)

__all__ = [
    "HeliacalEventKind",
    "VisibilityTargetKind",
    "LightPollutionClass",
    "LightPollutionDerivationMode",
    "ObserverAid",
    "VisibilityCriterionFamily",
    "LunarCrescentVisibilityClass",
    "VisibilityExtinctionModel",
    "VisibilityTwilightModel",
    "MoonlightPolicy",
    "ExtinctionCoefficient",
    "ObserverVisibilityEnvironment",
    "VisibilityPolicy",
    "VisibilitySearchPolicy",
    "VisibilityModel",
    "HeliacalPolicy",
    "AtmosphericExtinctionAssessment",
    "TwilightSkyBrightnessAssessment",
    "PointSourceVisibilityThreshold",
    "PhysicalVisibilityStatus",
    "PhysicalVisibilityEvidenceState",
    "PhysicalVisibilityPhase",
    "PhysicalVisibilityCrossingDirection",
    "PhysicalVisibilityBoundarySource",
    "PhysicalEventTimeSemantics",
    "PhysicalBackgroundScope",
    "PhysicalBackgroundComponentKind",
    "PhysicalAtmosphereInput",
    "PhysicalDirectionalBackground",
    "PhysicalModeledBackgroundComponent",
    "PhysicalSqmBackground",
    "PhysicalBortleBackground",
    "PhysicalHorizonSample",
    "PhysicalHorizonProfile",
    "PhysicalVisibilityPolicy",
    "VisibilityComponentReceipt",
    "PhysicalAtmosphereReceipt",
    "PhysicalValidityDomainReceipt",
    "PhysicalObserverProtocolReceipt",
    "PhysicalBackgroundReceipt",
    "PhysicalTargetReceipt",
    "PhysicalThresholdReceipt",
    "PhysicalVisibilityErrorBudgetReceipt",
    "PhysicalVisibilityAssessment",
    "PhysicalVisibilitySearchPolicy",
    "PhysicalObservationWindowReceipt",
    "PhysicalEventSolverReceipt",
    "PhysicalEventSensitivityReceipt",
    "PhysicalHorizonReceipt",
    "PhysicalEphemerisReceipt",
    "PhysicalVisibilityEventResult",
    "VisibilityDataPackConfig",
    "VisibilityDataPackReceipt",
    "LunarCrescentDetails",
    "VisibilityAssessment",
    "GeneralVisibilityEvent",
    "PlanetHeliacalEvent",
    "relative_optical_airmass",
    "atmospheric_extinction",
    "directional_twilight_sky_brightness",
    "point_source_visibility_threshold",
    "physical_visibility_assessment",
    "physical_visibility_event",
    "visibility_assessment",
    "visual_limiting_magnitude",
    "visibility_event",
    "visibility_tonight",
    "is_visible_tonight",
    "planet_heliacal_rising",
    "planet_heliacal_setting",
    "planet_acronychal_rising",
    "planet_acronychal_setting",
]
